local _, BUI = ...
local function Merge(base, overrides)
	local merged = {}
	for key, value in pairs(base) do
		merged[key] = type(value) == 'table' and Merge(value) or value
	end
	if overrides then
		for key, value in pairs(overrides) do
			merged[key] = type(value) == 'table' and Merge(value) or value
		end
	end
	return merged
end

local function ActionBarDefaults(overrides)
	local bar = {
		enabled            = false,
		buttonCount        = 12,
		buttonsPerRow      = 12,
		buttonSize         = 36,
		spacing            = 2,
		scale              = 100,
		centerHorizontally = false,
		posX               = 0,
		posY               = 0,
		anchorFrame        = '',
		anchorPoint        = 'BOTTOM',
		anchorOffsetX      = 0,
		anchorOffsetY      = 0,
		showHotkey         = true,
		showMacroText      = false,
		showCooldownText   = true,
		hideEmptyButtons   = false,
		clickThrough       = false,
		frameStrata        = 'MEDIUM',
		fadeEnabled        = false,
		fadeAlpha          = 30,
		fadeAnimated       = true,
		fadeDuration       = 0.2,
		pagingEnabled      = false,
		modifierPages      = { ctrl = 0, alt = 0, shift = 0 },
		alpha              = 100,
		growth             = 'TOPLEFT',
		buttonHeight       = 0,
		cooldownFontSize   = 14,
	}
	for key, value in pairs(overrides) do bar[key] = value end
	return bar
end

local CastBarBase = {
	enabled        = true,
	frameStrata    = 'LOW',
	textStrata     = 'HIGH',
	width          = 250,
	height         = 20,
	posX           = 0,
	posY           = 0,
	locked         = true,
	showIcon       = true,
	showTimer      = true,
	showTotalTime  = true,
	countdown      = true,
	showSpellName  = true,
	bgColor        = { 0.1, 0.1, 0.1, 0.8 },
	borderColor    = { 0, 0, 0, 1 },
	borderSize     = 1,
	textSize       = 12,
	textColor      = { 1, 1, 1, 1 },
	textOffsetX    = 0,
	textOffsetY    = 0,
	texture        = BUI.C.GLOBAL_OPTION,
	useSpellColors = false,
	useClassColor  = false,
	spellColors    = {},
	showLatency    = false,
	latencyColor   = { 1, 0, 0, 0.5 },
	interruptReadyColor = { 0, 1, 0, 1 },
	interruptTick      = true,
	interruptTickColor = { 1, 1, 1, 1 },
	interruptTickWidth = 2,
	interruptWindow    = false,
	interruptWindowColor = { 1, 0.82, 0, 0.8 },
	interruptTTS       = false,
	interruptTTSText   = 'Kick',
	interruptTTSSoon   = false,
	interruptTTSSoonText = 'Kick soon',
	interruptTTSSoonWindow = 4,
	pipWidth       = 2,
	pipColor       = { 1, 1, 1, 0.9 },
	pipGlow        = true,
	showCastTarget = false,
	channelTicks   = false,
	channelTickColor = { 0, 0, 0, 0.85 },
	channelTickWidth = 2,
	stageColors    = {},
	stageColorBackground = true,
	anchorFrame    = '',
	anchorPoint    = 'BOTTOM',
	anchorOffsetX  = 0,
	anchorOffsetY  = 0,
	matchAnchorWidth = false,
}

local BaseOpacity = {
	combat      = 100,
	outOfCombat = 100,
	mounted     = 100,
	flying      = 30,
	inInstance  = 100,
	override    = 0,
	vehicle     = 100,
	dead        = 50,
	petBattle   = 0,
}

local CdmViewerBase = {
	enabled               = true,
	iconWidth             = 38,
	iconHeight            = 38,
	spacing               = 1,
	zoom                  = 0.08,
	iconsPerRow           = 0,
	row2Count             = 0,
	row3Count             = 0,
	rowGrowth             = 'Down',
	centerLastRow         = true,
	vertical              = false,
	borderSize            = 1,
	borderColor           = { 0, 0, 0, 1 },
	textSize              = 16,
	textPosition          = 'BOTTOMRIGHT',
	textOffsetX           = 0,
	textOffsetY           = 0,
	textColor             = { 1, 1, 1, 1 },
	cooldownTextSize      = 14,
	cooldownTextPosition  = 'CENTER',
	cooldownTextOffsetX   = 0,
	cooldownTextOffsetY   = 0,
	cooldownTextColor     = { 1, 1, 1, 1 },
	showCooldownDecimals  = false,
	cooldownDecimalThreshold = 5,
	cooldownWarnSeconds   = 0,
	cooldownWarnColor     = { 1, 0.25, 0.25, 1 },
	showFlash             = false,
	showEdge              = false,
	reverseSwipe          = false,
	swipeColor            = { 0, 0, 0, 0.58 },
	centerHorizontally    = true,
	positionX             = 0,
	positionY             = 0,
	anchorFrame           = "",
	anchorPoint           = "BOTTOM",
	anchorOffsetX         = 0,
	anchorOffsetY         = 0,
}

local UnitFrameBase = {
	enabled           = true,
	width             = 200,
	height            = 40,
	powerHeight       = 8,
	showPower         = false,
	showName          = true,
	showHealthText    = true,
	showPowerText     = false,
	textSize          = 12,
	nameTextSize      = 12,
	healthTextSize    = 12,
	powerTextSize     = 10,
	namePosition      = 'LEFT',
	healthPosition    = 'RIGHT',
	powerPosition     = 'CENTER',
	nameOffsetX       = 0,
	nameOffsetY       = 0,
	healthOffsetX     = 0,
	healthOffsetY     = 0,
	powerOffsetX      = 0,
	powerOffsetY      = 0,
	hideRaidIcon      = false,
	hideLevel         = false,
	classColorName    = false,
	combatBorder      = false,
	combatBorderColor = { 0.8, 0.1, 0.1, 1 },
	aggroBorder       = false,
	aggroBorderColor  = { 1.0, 0.0, 0.0, 1 },
	debuffAnchorPoint         = 'TOPLEFT',
	debuffGrowthX             = 'RIGHT',
	debuffGrowthY             = 'UP',
	debuffOffsetX             = 0,
	debuffOffsetY             = 4,
	customTags                = {},
	powerPrediction           = false,
	powerPredictionColor      = { 1, 1, 1, 0.35 },

	debuffHighlightBorder       = true,
	debuffHighlightBar          = false,
	debuffHighlightClassFilter  = true,
	debuffHighlightTypeText     = false,
	debuffHighlightBadge        = true,
	debuffHighlightBadgeSize    = 24,
	debuffHighlightBadgeOffsetX = 0,
	debuffHighlightBadgeOffsetY = 0,
	auraReverseSwipe          = false,
	auraShowStack             = true,
	auraShowCd                = true,
	hostileNameColor  = { 0.937, 0.267, 0.267, 1 },
	neutralNameColor  = { 0.918, 0.702, 0.031, 1 },
	friendlyNameColor = { 0.133, 0.773, 0.369, 1 },
	anchorFrame       = '',
	anchorPoint       = 'RIGHT',
	anchorOffsetX     = 0,
	anchorOffsetY     = 0,
	matchAnchorWidth  = false,
	matchAnchorHeight = false,
	spacing           = 2,
	growthDirection   = 'DOWN',
	position          = { point = 'CENTER', relPoint = 'CENTER', x = 0, y = -200 },
}

BUI.Defaults = {
	global = {
		layoutStyle    = 'centered',
		navStyle       = 'default',
		navHighlight   = 'gradient',
	},
	profile = {
		general = {
			useClassColorTheme    = true,
			themeColor            = { 0.8313726186752319, 0, 0.3725490272045136, 1 },
			minimapButton         = { hide = false },
			font                  = BUI.C.DEFAULT_FONT,
			fontSlug              = false,
			texture               = BUI.C.DEFAULT_TEXTURE,
			gradientColor         = { 1, 1, 1, 1 },
			smoothBars            = true,
			showDecimalAbbreviations = false,
			ttsVoice              = -1,
			ttsVolume             = 100,
			soundChannel          = 'Master',
			visibilityPriority    = {'petBattle', 'dead', 'combat', 'vehicle', 'override', 'flying', 'mounted', 'inInstance'},
			visibilityOpacity     = Merge(BaseOpacity),
			visibilityModulesDisabled = {},
		},

		actionBars = {
			bars = {
				ActionBarDefaults({
					enabled = true,
					posY = 60,
					centerHorizontally = true,
					pagingEnabled = true,
					modifierPages = { ctrl = 0, alt = 0, shift = 0 },
				}),
				ActionBarDefaults({ posY = 100, centerHorizontally = true }),
				ActionBarDefaults({ posY = 140, centerHorizontally = true }),
				ActionBarDefaults({}),
				ActionBarDefaults({}),
				ActionBarDefaults({}),
				ActionBarDefaults({}),
				ActionBarDefaults({}),
			},
			petBar = ActionBarDefaults({ enabled = true, buttonCount = 10, buttonsPerRow = 10, buttonSize = 30, posY = 180, centerHorizontally = true, showHotkey = false }),
			stanceBar = ActionBarDefaults({ enabled = true, buttonCount = 10, buttonsPerRow = 10, buttonSize = 28, posY = 210, centerHorizontally = true }),
			vehicleBar = ActionBarDefaults({ enabled = true, buttonCount = 1, buttonsPerRow = 1, buttonSize = 40, posX = 320, posY = 60 }),
			microBar = ActionBarDefaults({ enabled = true, hidden = false, buttonsPerRow = 13, spacing = 0, vertical = false, posX = 420, posY = -380 }),
			bagBar = ActionBarDefaults({ enabled = true, hidden = false, posX = 620, posY = -380 }),
			extraBar = ActionBarDefaults({ enabled = true, hidden = false, posX = 0, posY = -250, blizzardArt = false }),
			cooldownColor  = { 1, 1, 1, 1 },
			cooldownAnchor = 'CENTER',
			cooldownOffsetX = 0,
			cooldownOffsetY = 0,
			cooldownThreshold = 0,
			cooldownThresholdColor = { 1, 0.25, 0.25, 1 },
			showCooldownDecimals = false,
			cooldownDecimalThreshold = 5,
			showItemRank   = true,
			itemRankSize   = 12,
			itemRankAnchor = 'TOPLEFT',
			itemRankOffsetX = 1,
			itemRankOffsetY = -1,
			swipeColor     = { 0, 0, 0, 0.8 },
			hotkeyFontSize = 11,
			hotkeyAnchor   = 'TOPRIGHT',
			hotkeyOffsetX  = -2,
			hotkeyOffsetY  = -3,
			hotkeyColor    = { 0.9, 0.9, 0.9, 1 },
			countFontSize  = 12,
			countAnchor    = 'BOTTOMRIGHT',
			countOffsetX   = -2,
			countOffsetY   = 3,
			countColor     = { 1, 1, 1, 1 },
			macroFontSize  = 10,
			macroAnchor    = 'BOTTOM',
			macroOffsetX   = 0,
			macroOffsetY   = 2,
			macroColor     = { 1, 1, 1, 1 },
			borderSize     = 1,
			borderColor    = { 0, 0, 0, 1 },
			petActiveColor = false,
			showAssistedCombat = false,
			emptyButtonBackground = true,
			emptyButtonColor = { 0, 0, 0, 0.22 },
			showKeyPresses = true,
			pressOpacity = 25,
			pressColor = { 1, 1, 1, 1 },
			procGlow = true,
			procGlowColor = { 1, 0.8, 0.3, 1 },
			procGlowStyle = 'proc',
			procGlowSpeed = 100,
			procGlowLines = 8,
			procGlowThickness = 1,
			castAnimation = true,
			snapBars = true,
			snapGap = 1,
			lockButtons = true,
			pickupKey = 'SHIFT',
		},

		modules = {
			actionBars    = false,
			unitFrames    = true,
			cdm           = true,
			castBars      = true,
			power         = true,
			minimap       = true,
			auras         = true,
			buffTracking  = true,
			datatext      = true,
			customBars    = true,
			cursor        = true,
			streamerTools = true,
			gemCounter    = true,
			markers       = false,
		},

		uiScale = {},


		socialShowBattleTag = true,

		socialAdvancedView = false,

		socialCollapsedSections = {},

		datatextSortState = {},

		interface = {
			minimapEnabled         = true,
			rotateMinimap          = true,
			minimapBorderWidth     = 2,
			minimapScale           = 120,
			minimapIconDock        = 'NONE',
			minimapIconSize        = 24,
			minimapClock           = true,
			minimapClock24h        = true,
			minimapClockServer     = false,
			minimapClockSize       = 12,
			minimapClockColor      = { r = 1, g = 1, b = 1 },
			minimapClockX          = 0,
			minimapClockY          = 0,
			minimapZone            = true,
			minimapZoneSize        = 11,
			minimapZoneColorCustom = false,
			minimapZoneColor       = { r = 1, g = 0.82, b = 0 },
			minimapZoneX           = 0,
			minimapZoneY           = 0,
			minimapHideMail        = false,
			minimapHideCrafting    = false,
			minimapHideGarrison    = false,
			minimapHideDifficulty  = false,
			minimapTextDifficulty  = false,
			minimapIconPos = {},
			drawerSide             = 'LEFT',
			drawerEnabled          = true,
			drawerX                = 0,
			drawerY                = 0,
			buttonBar = {
				enabled = false, side = 'BOTTOM', align = 'CENTER', size = 22, spacing = 1, perLine = 0,
				offsetX = 0, offsetY = 0, gap = 4, background = { 0.06, 0.06, 0.07, 1 }, excluded = {}, order = {},
			},
			skinBlizzardFrames     = false,
			fasterMovieSkip        = true,
			easyItemDestroy        = true,
			hideTalkingFrame       = true,
			hideRestedSleep        = true,
			hideErrorMessages      = true,
			hideZoneText           = true,
			worldMapZoneNames      = false,
			worldMapDungeonPins    = true,
		},

		moveFrames = {
			enabled           = true,
			positionMode      = 'remember',

			positions         = {},
		},

		alerts = {
			unlocked          = false,
			positioned        = false,
			posX              = 0,
			posY              = 0,
		},

		skinning = {
			merchant = false,
			trainer  = false,
			worldmap = true,
			gemcounter = false,
			experiencebar = false,
			characterFrame = false,
			chat = false,
			readycheck = true,
			readycheckScale = 1,
			staticpopup = true,
			staticpopupScale = 1,
			grouploot = true,
			loothistory = true,
			friends = true,
			groupfinder = true,
			queuepopups = true,
			mail = true,
			auctionhouse = true,
			journeys = true,
			collections = true,
			dressup = true,
			professions = true,
			spellbook = true,
			achievements = true,
			calendar = true,
			bonusroll = true,
			bonusrollHoldToRoll = true,
			inspect = true,
			trade = true,
			greatvault = true,
			questdialogs = true,
			systempanels = true,
			guild = true,
			itemsocketing = true,
			transmog = true,
			itemupgrade = true,
			splash = true,
			playerauras = true,
			playerAuraSettings = {
				font            = BUI.C.GLOBAL_OPTION,
				outline         = 'OUTLINE',
				timerSize       = 11,
				timerAnchor     = 'BOTTOM',
				timerOffsetX    = 0,
				timerOffsetY    = -12,
				stackSize       = 12,
				stackAnchor     = 'BOTTOMRIGHT',
				stackOffsetX    = -1,
				stackOffsetY    = 1,
			},
			chatSettings = {
				bgColor            = { 0.06, 0.06, 0.06 },
				bgAlpha            = 0.82,
				bgTexture          = 'SOLID',
				showBorder         = true,
				borderColor        = { 0, 0, 0 },
				borderThickness    = 1,
				insetX             = 5,
				insetTop           = 30,
				insetBottom        = 5,
				font               = 'GLOBAL',
				fontSize           = 14,
				fontFlags          = '',
				editFontSize       = 13,
				fontShadow         = false,
				tabFontSize        = 12,
				tabFontFlags       = '',
				tabUppercase       = false,
				selectedUseAccent  = true,
				selectedColor      = { 1, 1, 1 },
				inactiveColor      = { 0.82, 0.82, 0.85 },
				selectedAlpha      = 1,
				dockedAlpha        = 0.6,
				tabFlash           = true,
				flashColor         = { 1, 0.6, 0.1 },
				hideLogTab         = false,
				hoverTooltips      = true,
				timestamps         = false,
				timestampFormat    = '%H:%M',
				timestampColor     = { 0.6, 0.6, 0.6 },
				hideChannelNumbers = false,
				abbreviateChannels = false,
				scrollLines        = 3,
				urlCopy            = true,
				urlColor           = { 0, 0.66, 1 },
				editboxPosition    = 'BOTTOM',
				editHistory        = true,
				dragToMove         = true,
				msgFade            = false,
				msgFadeTime        = 120,
				mouseoverFade      = false,
				fadeDelay          = 2,
				showSizer          = true,
				sizerGrow          = 'UP',
				hideButtons        = true,
				hideVoiceButtons   = true,
				showCopyButton     = true,
			},
			objectivetrackerSettings = {
				font           = 'LIBRARY',
				fontSize       = 11,
				fontOutline    = false,
				cardOpacity    = 98,
				cardBorder     = true,
				cardTexture    = 'FLAT',
				showQuestIcons = false,
				showDashes     = false,
				maxHeight      = 700,
				scrollEnabled  = false,
				customColors   = true,
				colors = {
					title     = { 1, 0.82, 0.25 },
					hover     = { 1, 1, 1 },
					objective = { 0.85, 0.85, 0.9 },
					completed = { 0.45, 0.85, 0.45 },
					ready     = { 0.35, 1, 0.45 },
					timeLeft  = { 1, 0.45, 0.45 },
				},
			},
			experiencebarSettings = {
				barHeight      = 8,
				hoverHeight    = 18,
				fontSize       = 10,
				useAccentColor = true,
				xpColor        = { 0.8, 0.3, 1 },
				restedColor    = { 0.25, 0.4, 0.7 },
				showRestedXP   = true,
				position       = 'BOTTOM',
				barWidth       = 500,
				fullWidth      = true,
				posX           = 0,
				posY           = -250,
				locked         = true,
				centerH        = false,
			},
		},

		datatextEnabled = true,
		datatextHideHoversInCombat = true,
		datatextRosterTooltips = true,
		datatextBarsInit = false,

		datatextBars = {},

		datatextMinimap = {
			enabled        = false,
			fontSize       = 12,
			font           = BUI.C.GLOBAL_OPTION,
			colorValue     = { r = 0, g = 0.9019608497619629, b = 0.4313725829124451, a = 1 },
			spacing        = 1,
			anchor         = 'BOTTOM',
			gap            = 2,
			height         = 16,
			bgAlpha        = 0.8,
			bgColor        = { r = 0, g = 0, b = 0 },
			spread         = 0,
			border         = false,
			borderColor    = { r = 0.2, g = 0.2, b = 0.24, a = 1 },
			showFPS          = true,
			showPing         = true,
			pingSource       = 'world',
			showDurability   = false,
			showGold         = false,
			showIlvl         = false,
			showCoords       = false,
			showLootSpec     = false,
			showMemory       = false,
			showFriends      = false,
			showGuild        = false,
			showCombat       = false,
			showBags         = false,
			showMail         = false,
			showCurrency     = false,
			showTime         = false,
			bagsFormat       = 'FREE',
			time24           = false,
			timeLocal        = true,
			hideLabels       = false,
		},

		markers = {
			onlyInGroup    = false,
			tooltips       = true,
			showControls   = true,
			iconSize       = 22,
			spacing        = 4,
			countdownTime  = 5,
			countdownTime2 = 10,
			posX           = 0,
			posY           = -240,
			anchorFrame    = "",
			anchorPoint    = "BOTTOM",
			anchorOffsetX  = 0,
			anchorOffsetY  = 0,
			matchAnchorWidth = false,
			alpha          = 100,
			fadeEnabled    = false,
			fadeAlpha      = 0,
			fadeAnimated   = true,
			fadeDuration   = 0.2,
		},

		cursor = {
			enabled    = false,
			combatOnly = false,
			hideOverMenus = false,
			size       = 30,
			slots = {
				inner = {
					enabled = false,
					kind    = 'click',
					offset  = -8,
					zOrder  = 3,
					colorR  = 0.925,
					colorG  = 0,
					colorB  = 1,
					alpha   = 0.8,
				},
				main = {
					enabled = true,
					kind    = 'static',
					offset  = 0,
					zOrder  = 2,
					colorR  = 1,
					colorG  = 1,
					colorB  = 1,
					alpha   = 0.8,
				},
				outer = {
					enabled = false,
					kind    = 'gcd',
					offset  = 8,
					zOrder  = 1,
					colorR  = 0.6,
					colorG  = 0.85,
					colorB  = 1,
					alpha   = 0.9,
				},
			},
		},

		hunterTip = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			posX              = 0,
			posY              = -100,
			displayMode       = 'BARS',
			hideWhenEmpty     = false,
			showOnlyInCombat  = false,
			colorByStacks     = false,
			barWidth          = 80,
			barHeight         = 18,
			barSpacing        = 4,
			borderThickness   = 1,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 1,   g = 1,   b = 1,   a = 1 },
			filledColor       = { r = 0.2, g = 0.8, b = 0.2, a = 1 },
			emptyColor        = { r = 0.2, g = 0.2, b = 0.2, a = 0.6 },
			borderColor       = { r = 0,   g = 0,   b = 0,   a = 1 },
			stack1Color       = { r = 0.2, g = 1.0, b = 0.2, a = 1 },
			stack2Color       = { r = 1.0, g = 0.85, b = 0.2, a = 1 },
			stack3Color       = { r = 1.0, g = 0.2, b = 0.2, a = 1 },
		},

		hunterCobraFang = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = '',
			posX              = 0,
			posY              = -130,
			textSize          = 24,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 0.35, g = 0.95, b = 0.3, a = 1 },
			sound             = 'None',
		},

		hunterPreciseShots = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'PS',
			posX              = 0,
			posY              = -100,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 0.2, g = 0.6, b = 1.0, a = 1 },
			sound             = 'None',
		},

		hunterBulletstorm = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'AiS',
			posX              = 0,
			posY              = -130,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 1.0, g = 0.72, b = 0.2, a = 1 },
			sound             = 'None',
		},

		hunterLockAndLoad = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'LnL',
			posX              = 0,
			posY              = -140,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 1.0, g = 0.85, b = 0.2, a = 1 },
			sound             = 'None',
		},

		hunterKillCommand = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'KC',
			posX              = 0,
			posY              = -100,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 1.0, g = 0.4, b = 0.2, a = 1 },
			sound             = 'None',
		},

		hunterRaptorSwipe = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'RS',
			customTextAlt     = 'RS!',
			posX              = 0,
			posY              = -100,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 0.95, g = 0.6, b = 0.2, a = 1 },
			sound             = 'None',
		},

		hunterRaptorPrompt = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'RAPTOR',
			posX              = 0,
			posY              = -130,
			textSize          = 20,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 1.0, g = 0.85, b = 0.2, a = 1 },
			sound             = 'None',
		},

		monkVivaciousVivification = {
			enabled           = false,
			showAnchor        = false,
			centerHorizontally = true,
			customText        = 'VIVIFY!',
			posX              = 0,
			posY              = -100,
			textSize          = 22,
			font              = BUI.C.GLOBAL_OPTION,
			textColor         = { r = 0.55, g = 0.9, b = 1.0, a = 1 },
			sound             = 'None',
		},

		petAlert = {
			enabled            = false,
			showAnchor         = false,
			centerHorizontally = true,
			posX               = 0,
			posY               = 140,
			customText         = 'PET ATTACK!',
			textSize           = 22,
			font               = BUI.C.GLOBAL_OPTION,
			textColor          = { r = 1, g = 0.2, b = 0.2, a = 1 },
			sound              = 'None',
		},

		gatewayAlert = {
			enabled            = false,
			showAnchor         = false,
			centerHorizontally = true,
			posX               = 0,
			posY               = 100,
			customText         = 'GATEWAY READY',
			textSize           = 22,
			font               = BUI.C.GLOBAL_OPTION,
			textColor          = { r = 0.35, g = 1, b = 0.45, a = 1 },
			sound              = 'None',
		},

		killCommandOverlay = {
			enabled            = false,
			showTimer          = true,
			showBeastName      = true,
			showDecimals       = true,
			decimalThreshold   = 5,
			timerSize          = 20,
			beastSize          = 12,
			timerAnchor        = 'TOPLEFT',
			timerOffsetX       = 2,
			timerOffsetY       = -2,
			timerColor         = { r = 1, g = 1, b = 1 },
			beastAnchor        = 'BOTTOM',
			beastOffsetX       = 0,
			beastOffsetY       = -2,
		},

		bestialWrathOverlay = {
			enabled          = false,
			displayMode      = 'icon',
			showHoldThrash   = true,
			textSize         = 13,
			textAnchor       = 'CENTER',
			textOffsetX      = 0,
			textOffsetY      = 0,
			screenTextSize   = 28,
			screenLocked     = true,
			screenCombatOnly = true,
			tts              = false,
			ttsHold          = true,
			posX             = 0,
			posY             = 120,
			anchorFrame      = '',
			anchorPoint      = 'BOTTOM',
			anchorOffsetX    = 0,
			anchorOffsetY    = 0,
		},

		smartMisdirect = {
			enabled        = false,
			useFocus       = true,
			preferTank     = true,
			tankMethod     = 'roleOnly',
			fallbackPet    = true,
			overrideName   = '',
			overrideRealm  = '',
		},

		misdirectAlert = {
			enabled            = false,
			alertMode          = 'flash',
			flashSeconds       = 2,
			flashOnCast        = true,
			flashOnTargetChange = true,
			showAnchor         = false,
			centerHorizontally = true,
			posX               = 0,
			posY               = 170,
			customText         = 'MD',
			textSize           = 22,
			font               = BUI.C.GLOBAL_OPTION,
			textColor          = { r = 0.3, g = 0.9, b = 1, a = 1 },
			sound              = 'None',
		},

		packLeader = {
			enabled            = false,
			showAnchor         = false,
			posX               = 0,
			posY               = -180,
			anchorFrame        = '',
			anchorPoint        = 'BOTTOM',
			anchorOffsetX      = 0,
			anchorOffsetY      = 0,
			showOnlyInCombat   = false,
			iconSize           = 36,
			nextIconSize       = 20,
			showNextIcon       = true,
			spacing            = 2,
			glowOnReady        = true,
			animateTransitions = true,
			showCountdownText  = true,
			labelTextSize      = 12,
			showNextText       = true,
			topTextOffsetX     = 0,
			topTextOffsetY     = 2,
			bottomTextOffsetX  = 0,
			bottomTextOffsetY  = -2,
			beastColors = {
				boar   = { r = 0.92, g = 0.52, b = 0.13 },
				bear   = { r = 0.60, g = 0.38, b = 0.22 },
				wyvern = { r = 0.28, g = 0.78, b = 0.52 },
			},
		},

		powerScope = 'spec',
		powerVariants = {},

		powerBar = {
			enabled            = false,
			frameStrata        = 'MEDIUM',
			textStrata         = 'MEDIUM',
			showPrediction     = false,
			predictionColorR   = 1,
			predictionColorG   = 1,
			predictionColorB   = 1,
			predictionColorA   = 0.35,
			posX               = 0,
			posY               = -73,
			textSize           = 26,
			locked             = true,
			centerHorizontally = true,
			anchorFrame        = '',
			anchorPoint        = 'BOTTOM',
			anchorOffsetX      = 0,
			anchorOffsetY      = -5,
			matchAnchorWidth   = false,
			textColorR         = 1,
			textColorG         = 1,
			textColorB         = 1,
			classColorPower    = true,
			hidePercentSign    = false,
			barMode            = true,
			barWidth           = 200,
			barHeight          = 16,
			barColorR          = 0.2,
			barColorG          = 0.6,
			barColorB          = 1,
			barBgColorR        = 0.1,
			barBgColorG        = 0.1,
			barBgColorB        = 0.1,
			barBgColorA        = 1,
			barTextSize        = 14,
			barTextColorR      = 1,
			barTextColorG      = 1,
			barTextColorB      = 1,
			barTextOffsetX     = 0,
			barTextOffsetY     = 0,
			barTextAbove       = false,
			barHideText        = false,
			tickMarks          = {},
			tickMarkColor      = { 1, 1, 1, 0.6 },
			tickMarkWidth      = 1,
			borderSize         = 1,
			borderColor        = { 0, 0, 0, 1 },
			lowPowerEnabled    = false,
			lowPowerThreshold  = 30,
			highPowerThreshold = 70,
			lowPowerColorR     = 1,
			lowPowerColorG     = 0.2,
			lowPowerColorB     = 0.2,
			medPowerColorR     = 1,
			medPowerColorG     = 1,
			medPowerColorB     = 0.2,
		},

		powerBar2 = {
			indicators = {
				[1] = {
					enabled         = false,
					bar             = 'secondary',
					source          = 'mana',
					format          = 'percent_pct',
					anchor          = 'TOP',
					offsetX         = 0,
					offsetY         = 14,
					size            = 13,
					layer           = 5,
					colorR          = 0.4,
					colorG          = 0.6,
					colorB          = 1.0,
				},
				[2] = {
					enabled         = false,
					bar             = 'secondary',
					source          = 'mana',
					format          = 'percent_pct',
					anchor          = 'BOTTOM',
					offsetX         = 0,
					offsetY         = -14,
					size            = 13,
					layer           = 5,
					colorR          = 1.0,
					colorG          = 0.85,
					colorB          = 0.4,
				},
				[3] = {
					enabled         = false,
					bar             = 'primary',
					source          = 'mana',
					format          = 'percent_pct',
					anchor          = 'TOP',
					offsetX         = 0,
					offsetY         = 14,
					size            = 13,
					layer           = 5,
					colorR          = 0.4,
					colorG          = 0.6,
					colorB          = 1.0,
				},
				[4] = {
					enabled         = false,
					bar             = 'primary',
					source          = 'mana',
					format          = 'percent_pct',
					anchor          = 'BOTTOM',
					offsetX         = 0,
					offsetY         = -14,
					size            = 13,
					layer           = 5,
					colorR          = 1.0,
					colorG          = 0.85,
					colorB          = 0.4,
				},
			},
		},

		secondaryPower = {
			enabled            = true,
			textStrata         = 'HIGH',
			posX               = 0,
			posY               = 0,
			textSize           = 26,
			locked             = true,
			centerHorizontally = true,
			anchorFrame        = '',
			anchorPoint        = 'BOTTOM',
			anchorOffsetX      = 0,
			anchorOffsetY      = -5,
			matchAnchorWidth   = false,
			textColorR         = 1,
			textColorG         = 1,
			textColorB         = 1,
			textOffsetX        = 0,
			textOffsetY        = 0,
			useClassColor      = true,
			borderSize         = 1,
			borderColor        = { 0, 0, 0, 1 },
			lowPowerEnabled    = false,
			lowPowerThreshold  = 30,
			highPowerThreshold = 70,
			lowPowerColorR     = 1,
			lowPowerColorG     = 0.2,
			lowPowerColorB     = 0.2,
			medPowerColorR     = 1,
			medPowerColorG     = 1,
			medPowerColorB     = 0.2,

			runeTotalWidth      = 240,
			runeHeight          = 12,
			runeSpacing         = 0,
			runeShowMax         = true,
			runeNumberOnly      = true,
			runeBarOffsetX      = 0,
			runeBarOffsetY      = 0,
			runeTextSize        = 26,
			runeTextColorR      = 1,
			runeTextColorG      = 1,
			runeTextColorB      = 1,
			runeTextOffsetX     = 0,
			runeTextOffsetY     = 0,
			showRuneCooldown    = true,
			runeCooldownSize    = 10,
			runeCooldownColorR  = 1,
			runeCooldownColorG  = 1,
			runeCooldownColorB  = 1,
			runeRechargingColorR = 0.4,
			runeRechargingColorG = 0.4,
			runeRechargingColorB = 0.4,
			staggerBarMode    = true,
			staggerBarWidth   = 200,
			staggerBarHeight  = 16,
			staggerValueSize  = 14,
			staggerValueOffsetX = 0,
			staggerValueOffsetY = 0,
			staggerHideBarText  = false,
			staggerTextColorR   = 1,
			staggerTextColorG   = 1,
			staggerTextColorB   = 1,
			staggerShowPercent  = true,
			staggerShowValue    = true,
			staggerLightColorR    = 0.52,
			staggerLightColorG    = 1.0,
			staggerLightColorB    = 0.52,
			staggerModerateColorR = 1.0,
			staggerModerateColorG = 0.98,
			staggerModerateColorB = 0.35,
			staggerHeavyColorR    = 1.0,
			staggerHeavyColorG    = 0.42,
			staggerHeavyColorB    = 0.42,

			runeColorR          = 0.77,
			runeColorG          = 0.12,
			runeColorB          = 0.23,
			runeBgColorR        = 0.15,
			runeBgColorG        = 0.15,
			runeBgColorB        = 0.15,
			runeBgColorA        = 1,

			staggerColorR          = 0.52,
			staggerColorG          = 1.00,
			staggerColorB          = 0.52,
			staggerBgColorR        = 0.15,
			staggerBgColorG        = 0.15,
			staggerBgColorB        = 0.15,
			staggerBgColorA        = 1,
			staggerBarOffsetX      = 0,
			staggerBarOffsetY      = 0,
			staggerValueColorR     = 1,
			staggerValueColorG     = 1,
			staggerValueColorB     = 1,

			casterManaBarMode      = false,
			casterManaBarWidth     = 200,
			casterManaBarHeight    = 16,
			casterManaColorR       = 1,
			casterManaColorG       = 1,
			casterManaColorB       = 1,
			casterManaBgColorR     = 0.1,
			casterManaBgColorG     = 0.1,
			casterManaBgColorB     = 0.1,
			casterManaBgColorA     = 1,
			casterManaBarOffsetX   = 0,
			casterManaBarOffsetY   = 0,
			casterManaHideBarText  = false,
			casterManaShowValue    = true,
			casterManaShowPercent  = false,
			casterManaValueColorR  = 1,
			casterManaValueColorG  = 1,
			casterManaValueColorB  = 1,
			casterManaValueOffsetX = 0,
			casterManaValueOffsetY = 0,
			casterManaValueSize    = 14,

			overrideBarMode         = true,
			overrideBarWidth        = 200,
			overrideBarHeight       = 16,
			overrideColorR          = 0.20,
			overrideColorG          = 0.60,
			overrideColorB          = 1.00,
			overrideBgColorR        = 0.15,
			overrideBgColorG        = 0.15,
			overrideBgColorB        = 0.15,
			overrideBgColorA        = 1,
			overrideBarOffsetX      = 0,
			overrideBarOffsetY      = 0,
			overrideHideBarText     = false,
			overrideShowValue       = true,
			overrideShowPercent     = false,
			overrideTextColorR      = 1,
			overrideTextColorG      = 1,
			overrideTextColorB      = 1,
			overrideValueColorR     = 1,
			overrideValueColorG     = 1,
			overrideValueColorB     = 1,
			overrideValueOffsetX    = 0,
			overrideValueOffsetY    = 0,
			overrideValueSize       = 14,

			soulFragsBarMode         = true,
			soulFragsBarWidth        = 200,
			soulFragsBarHeight       = 16,
			soulFragsColorR          = 0.40,
			soulFragsColorG          = 1.00,
			soulFragsColorB          = 0.40,
			soulFragsBgColorR        = 0.15,
			soulFragsBgColorG        = 0.15,
			soulFragsBgColorB        = 0.15,
			soulFragsBgColorA        = 1,
			soulFragsBarOffsetX      = 0,
			soulFragsBarOffsetY      = 0,
			soulFragsHideBarText     = false,
			soulFragsShowValue       = true,
			soulFragsShowPercent     = true,
			soulFragsTextColorR      = 1,
			soulFragsTextColorG      = 1,
			soulFragsTextColorB      = 1,
			soulFragsValueColorR     = 1,
			soulFragsValueColorG     = 1,
			soulFragsValueColorB     = 1,
			soulFragsValueOffsetX    = 0,
			soulFragsValueOffsetY    = 0,
			soulFragsValueSize       = 14,
		},

		cdm = {
			syncViewers          = false,
			allowIndividualMove   = false,
			allowIndividualResize = true,
			disableSnapping      = false,
			showBlizzardOverlay  = true,
			showBuffDuration     = true,
			glow = {
				enabled   = true,
				type      = 'pixel',
				color     = { 0.95, 0.95, 0.32, 1 },
				speed     = 100,
				lines     = 8,
				thickness = 1,
			},
			assist = {
				color = { 0.3, 0.7, 1.0, 1 },
			},
			pressHighlight = {
				enabled      = false,
				showTint     = true,
				overlayStyle = 'tint',
				tintColor    = { 1, 1, 1, 0.3 },
				showBorder   = false,
				borderColor  = { 1, 1, 1, 1 },
			},
			essential = Merge(CdmViewerBase, { iconWidth = 50, iconHeight = 50, spacing = 1, positionY = -200, hiddenSlots = {}, detachedIcons = {}, showKeybinds = false, keybindAnchor = 'TOPRIGHT', keybindFontSize = 12, keybindOffsetX = 2, keybindOffsetY = 2, keybindFont = BUI.C.GLOBAL_OPTION, keybindColor = { 1, 1, 1, 1 }, customSpells = {}, iconOrder = {}, hiddenIcons = {}, iconOverrides = {}, buffTracking = {}, showOnlyOnCD = {} }),
			utility   = Merge(CdmViewerBase, { iconWidth = 50, iconHeight = 50, spacing = 1, iconsPerRow = 6, positionY = -251, hiddenSlots = {}, detachedIcons = {}, showKeybinds = false, keybindAnchor = 'TOPRIGHT', keybindFontSize = 12, keybindOffsetX = 2, keybindOffsetY = 2, keybindFont = BUI.C.GLOBAL_OPTION, keybindColor = { 1, 1, 1, 1 }, customSpells = {}, iconOrder = {}, hiddenIcons = {}, iconOverrides = {}, buffTracking = {}, showOnlyOnCD = {} }),
			buffs     = Merge(CdmViewerBase, { iconWidth = 36, iconHeight = 36, spacing = 1, textSize = 19, cooldownTextSize = 23, positionY = -126, hiddenSlots = {}, detachedIcons = {}, customSpells = {}, iconOrder = {}, hiddenIcons = {}, iconOverrides = {}, buffTracking = {} }),
			buffBars = {
				skinEnabled    = true,
				anchorFrame    = '',
				anchorPoint    = 'BOTTOM',
				anchorOffsetX  = 0,
				anchorOffsetY  = 0,
				matchAnchorWidth = false,
				positionX      = 0,
				positionY      = -300,
				centerHorizontally = false,
				growDirection  = 'DOWN',
				showIcon       = true,
				showName       = true,
				showDuration   = true,
				showStacks     = true,
				iconSize       = 30,
				barWidth       = 220,
				barHeight      = 22,
				spacing        = 2,
				borderSize     = 1,
				borderColor    = { 0, 0, 0, 1 },
				bgColor        = { 0.1, 0.1, 0.1, 0.85 },
				nameSize       = 11,
				durationSize   = 11,
				stackSize      = 11,
				useClassColor  = false,
				barColor       = { 1, 0.5, 0.25, 1 },
			},
		},

		gcdHistory = {
			enabled          = false,
			locked           = true,
			iconSize         = 40,
			maxIcons         = 8,
			spacing          = 1,
			growDirection    = 'RIGHT',
			fadeOldIcons     = true,
			fadeTime         = 5,
			borderSize       = 1,
			borderColor      = { 0, 0, 0, 1 },
			zoom             = 0.08,
			posX             = 0,
			posY             = 0,
			anchorFrame      = '',
			anchorPoint      = 'BOTTOM',
			anchorOffsetX    = 0,
			anchorOffsetY    = 0,
			hideAutoAttacks  = true,
			showActiveCast   = true,
			activeCastScale  = 1.3,
			blacklist        = {},
		},

		castBars = {
			player = Merge(CastBarBase, {
				barColor      = { 0.4, 0.6, 1.0, 1.0 },
				width         = 284,
				posX          = 0,
				posY          = -164,
				useSpellColors = true,
			}),
			target = Merge(CastBarBase, {
				barColor          = { 0.01568627543747425, 1, 0, 1.0 },
				interruptColor    = { 1, 0, 0.08627451211214066, 1.0 },
				interruptOnCDColor = { 0.9, 0.5, 0.0, 1.0 },
				width          = 254,
				height         = 42,
				posX           = 312,
				posY           = -269,
				anchorFrame    = 'BUI_TargetFrame',
				anchorOffsetX  = 13,
				anchorOffsetY  = -27,
			}),
			focus = Merge(CastBarBase, {
				barColor          = { 0.6, 0.2, 0.8, 1.0 },
				interruptColor    = { 0.7, 0.2, 0.2, 1.0 },
				interruptOnCDColor = { 0.9, 0.5, 0.0, 1.0 },
				posX           = 295,
				posY           = -51,
				anchorFrame    = 'BUI_TargetFrame',
				anchorOffsetY  = 200,
			}),
			boss = Merge(CastBarBase, {
				barColor             = { 0.8, 0.2, 0.2, 1.0 },
				interruptColor       = { 0.4, 0.1, 0.1, 1.0 },
				interruptOnCDColor   = { 0.9, 0.5, 0.0, 1.0 },
				height               = 16,
				useIndividualColors  = false,
				bossColors = {
					{ 0.8, 0.2, 0.2, 1.0 },
					{ 0.2, 0.6, 0.8, 1.0 },
					{ 0.2, 0.8, 0.3, 1.0 },
					{ 0.8, 0.6, 0.2, 1.0 },
					{ 0.6, 0.2, 0.8, 1.0 },
				},
			}),
		},

		customBars = {},

		social = {
			autoAcceptParty = true,
			autoConfirmRole = false,
			includeGuild    = true,
		},

		automation = {
			fasterLooting          = true,
			autoRepair             = true,
			autoRepairGuildFunds   = true,
			autoRepairShowSummary  = true,
			sellJunk               = true,
			autoKeystone           = true,
			autoAcceptQuests       = false,
			autoCompleteQuests     = false,
			castOnKeyDown          = true,
			ahCurrentExpansionOnly = true,
		},

		combatLogging = {
			enabled         = false,
			raids           = true,
			mythicPlus      = true,
			otherDungeons   = false,
			delves          = false,
			arenas          = false,
			battlegrounds   = false,
			advancedLogging = true,
			chatMessage     = true,
			showIndicator   = true,
			showAnchor      = false,
			posX            = 0,
			posY            = 300,
		},

		framePositions = {},

		auras = {
			locked                      = true,
			petWarningsEnabled          = false,
			petAttackWarning            = { enabled = false },
			petDeadWarning              = { enabled = false },
			petHealthWarning            = { enabled = false, threshold = 40 },
			grimoireSacrificeWarning    = { enabled = false },
			playDeadWarning             = { enabled = true },
			warningColor                = { r = 1, g = 1, b = 1, a = 1 },
			fontSize                    = 28,
			font                        = BUI.C.GLOBAL_OPTION,
			posX                        = 0,
			posY                        = 119,
			centerHorizontally          = false,

			anchorFrame                 = "",
			anchorPoint                 = "BOTTOM",
			anchorOffsetX               = 0,
			anchorOffsetY               = 0,
			lowHpWarning                = false,
			lowHpThreshold              = 50,
			lowHpText                   = 'HEAL',
			lowHpFontSize               = 28,
			lowHpFont                   = BUI.C.GLOBAL_OPTION,
			lowHpColor                  = { r = 1, g = 0.2, b = 0.2, a = 1 },
			lowHpPosX                   = 0,
			lowHpPosY                   = 200,
			markWarning                 = false,
			markText                    = "Hunter's Mark",
			markFontSize                = 24,
			markFont                    = BUI.C.GLOBAL_OPTION,
			markColor                   = { r = 1, g = 0.25, b = 0.35, a = 1 },
			markShowIcon                = false,
			markPulse                   = true,
			markPosX                    = 0,
			markPosY                    = -150,
			markAnchorFrame             = "",
			markAnchorPoint             = "BOTTOM",
			markAnchorOffsetX           = 0,
			markAnchorOffsetY           = 0,
			markLocked                  = true,
			markCombatOnly              = false,
			markGroupOnly               = false,
			markHideInTown              = false,
			lowHpLocked                 = true,

			lowHpCenterHorizontally     = false,
			lowHpAnchorFrame            = "",
			lowHpAnchorPoint            = "BOTTOM",
			lowHpAnchorOffsetX          = 0,
			lowHpAnchorOffsetY          = 0,
		},

		auraFilters = {
			debuffWhitelist     = {},
			debuffBlacklist     = {},
			buffWhitelist       = {},
			buffBlacklist       = {},
			buffWhitelistOnly   = false,
			debuffWhitelistOnly = false,
			shareBlacklists     = false,
		},

		recentAuras = {
			debuff = {},
			buff   = {},
		},

		combatMessage = {
			enabled            = false,
			locked             = true,
			posX               = 0,
			posY               = -100,
			centerHorizontally = true,
			anchorFrame        = "",
			anchorPoint        = "BOTTOM",
			anchorOffsetX      = 0,
			anchorOffsetY      = 0,
			fontSize           = 18,
			font               = BUI.C.GLOBAL_OPTION,
			enterColor         = { 1, 0.2, 0.2, 1 },
			leaveColor         = { 0.2, 1, 0.2, 1 },
			fadeTime           = 0.8,
		},

		combatTimer = {
			enabled            = false,
			locked             = true,
			posX               = 0,
			posY               = 150,
			centerHorizontally = false,
			anchorFrame        = "",
			anchorPoint        = "BOTTOM",
			anchorOffsetX      = 0,
			anchorOffsetY      = 0,
			fontSize           = 20,
			showMilliseconds   = false,
			font               = BUI.C.GLOBAL_OPTION,
			colorR             = 1,
			colorG             = 1,
			colorB             = 1,
		},

		crosshair = {
			enabled          = false,
			style            = 'cross',
			size             = 20,
			thickness        = 2,
			gap              = 4,
			colorR           = 1,
			colorG           = 1,
			colorB           = 1,
			alpha            = 0.8,
			offsetX          = 0,
			offsetY          = 0,
			hideOutOfCombat  = false,
			hideInTown       = false,
			rangeIndicator   = false,
			inRangeColor     = { 0, 1, 0 },
			outOfRangeColor  = { 1, 0, 0 },
		},

		cdAnnouncer = {
			enabled            = false,
			showAnchor         = false,
			hideUnusable       = false,
			centerHorizontally = false,
			posX               = 0,
			posY               = 0,
			font               = BUI.C.GLOBAL_OPTION,
			cdColor            = { r = 1,   g = 1,    b = 1,   a = 1 },
			readyColor         = { r = 0.4, g = 1,    b = 0.4, a = 1 },

			charSpells         = {},
		},

		bloodlust = {
			enabled            = false,
			posX               = 0,
			posY               = 200,
			centerHorizontally = true,
			anchorFrame        = "",
			anchorPoint        = "BOTTOM",
			anchorOffsetX      = 0,
			anchorOffsetY      = 0,
			font               = BUI.C.GLOBAL_OPTION,
			fontSize           = 16,
			showIcon           = true,
			iconSize           = 22,

			usedFormat         = '[spell] used!',
			usedHoldDuration   = 3,
			usedColor          = { 1, 0.85, 0.25, 1 },
			flashOnUsed        = true,
			flashDuration      = 0.6,
			soundOnUsed        = 'None',
			ttsOnUsed          = false,
			ttsUsedText        = 'Lust used',

			showWhenActive     = true,
			activeFormat       = 'Lust [time]',
			activeColor        = { 0.4, 1, 0.4, 1 },

			showWhenCD         = false,
			cdFormat           = 'Lust [time]',
			cdColor            = { 1, 0.55, 0.4, 1 },
			warnBeforeReady    = 0,
			soundOnWarn        = 'None',
			ttsOnWarn          = false,
			ttsWarnText        = 'Lust soon',

			showWhenReady      = false,
			readyFormat        = 'Lust Ready',
			readyColor         = { 0.4, 1, 0.4, 1 },
			readyHoldDuration  = 2,
			flashOnReady       = true,
			flashReadyDuration = 0.9,
			soundOnReady       = 'None',
			ttsOnReady         = false,
			ttsReadyText       = 'Lust ready',
		},

		unitFrames = {
			enabled               = true,
			showTooltips          = true,
			clickToTarget         = true,
			texture               = BUI.C.GLOBAL_OPTION,
			font                  = BUI.C.GLOBAL_OPTION,
			textSize              = 12,
			nameTextSize          = 12,
			healthTextSize        = 12,
			powerTextSize         = 10,
			borderSize            = 1,
			borderColor           = { 0, 0, 0, 1 },
			combatBorder          = false,
			combatBorderColor     = { 0.8, 0.1, 0.1, 1 },
			healthColor           = { 0.2, 0.8, 0.2, 1 },
			powerColor            = { 0.2, 0.4, 0.8, 1 },
			bgColor               = { 0.1, 0.1, 0.1, 0.8 },
			shieldEnabled         = true,
			shieldColor           = { 0, 1, 0.239, 0.5 },
			shieldDirection       = 'right',
			shieldOverlay         = 'Stripes',
			healAbsorbEnabled     = true,
			healAbsorbColor       = { 0.9, 0.1, 0.1, 0.6 },
			healAbsorbDirection   = 'left',
			healAbsorbOverlay     = 'Stripes',
			petHealthColor        = { 0.2, 0.8, 0.2, 1 },
			petPowerColor         = { 0.2, 0.4, 0.8, 1 },
			petBgColor            = { 0.1, 0.1, 0.1, 0.8 },
			petPowerBgColor       = { 0.1, 0.1, 0.1, 0.8 },
			petBorderColor        = { 0, 0, 0, 1 },
			dispelRecolor         = true,
			dispelBlend           = false,
			dispelOpacity         = 100,
			transparentHealth     = false,
			healthBarAlpha        = 0.35,
			classColorHealth      = true,
			classColorPower       = true,
			useClassColorPowerBar = false,
			showName              = false,
			showHealthText        = false,
			showPowerText         = false,
			healthFormat          = '[hp:short] • [perhp]%',
			powerFormat           = '[perpp]%',
			nameFormat            = '[name]',
			showBuffs             = false,
			showDebuffs           = false,
			syncPlayerTarget      = false,
			excludePetFromSync    = false,
			raidIconMode          = 'icon',
			raidIconPosition      = 'TOP',
			raidIconOffsetX       = 0,
			raidIconOffsetY       = 0,
			raidIconSize          = 16,
			leaderIconEnabled     = false,
			leaderIconPosition    = 'TOPLEFT',
			leaderIconOffsetX     = -4,
			leaderIconOffsetY     = 6,
			leaderIconSize        = 14,
			showLevel             = false,
			levelPosition         = 'BOTTOMLEFT',
			levelOffsetX          = 0,
			levelOffsetY          = 0,
			levelTextSize         = 10,
			levelFormat           = '[level]',

			player = Merge(UnitFrameBase, {
				width             = 271,
				height            = 41,
				powerHeight       = 11,
				showPower         = true,
				showPowerText     = true,
				powerTextSize     = 11,
				combatBorder      = true,
				combatBorderColor = { 0.8, 0.1, 0.1, 1 },
				classColorName    = false,
				customName        = '',
				position          = { point = 'CENTER', relPoint = 'CENTER', x = -290, y = -195 },
			}),

			target = Merge(UnitFrameBase, {
				width                   = 271,
				height                  = 41,
				powerHeight             = 11,
				showPower               = true,
				showPowerText           = true,
				classColorName          = false,
				position                = { point = 'CENTER', relPoint = 'CENTER', x = 290, y = -195 },
				showDebuffs             = true,
				showBuffs               = true,
				debuffShowMode          = 'mine',
				buffShowMode            = 'all',
				auraIconSize            = 22,
				auraSpacing             = 2,
				auraStackSize           = 10,
				auraCdSize              = 10,
				maxDebuffs              = 8,
				maxBuffs                = 16,
				debuffsPerRow           = 8,
				buffsPerRow             = 8,
				debuffStackPos          = 'BOTTOMRIGHT',
				buffAnchorPoint         = 'BOTTOMLEFT',
				buffOffsetX             = 0,
				buffOffsetY             = -4,
				buffGrowthX             = 'RIGHT',
				buffGrowthY             = 'DOWN',
				buffStackPos            = 'BOTTOMRIGHT',
				showDebuffType          = true,
			}),

			targettarget = Merge(UnitFrameBase, {
				width          = 110,
				height         = 30,
				showHealthText = false,
				nameTextSize   = 10,
				healthTextSize = 10,
				powerTextSize  = 8,
				position       = { point = 'CENTER', relPoint = 'CENTER', x = 481, y = -195 },
				anchorFrame    = '',
				anchorPoint    = 'RIGHT',
				anchorOffsetX  = 5,
				anchorOffsetY  = 0,

				showDebuffs             = true,
				showBuffs               = false,
				debuffShowMode          = 'mine',
				buffShowMode            = 'all',
				auraIconSize            = 18,
				auraSpacing             = 2,
				auraStackSize           = 10,
				auraCdSize              = 10,
				maxDebuffs              = 6,
				maxBuffs                = 8,
				debuffsPerRow           = 6,
				buffsPerRow             = 6,
				debuffStackPos          = 'BOTTOMRIGHT',
				buffAnchorPoint         = 'BOTTOMLEFT',
				buffOffsetX             = 0,
				buffOffsetY             = -4,
				buffGrowthX             = 'RIGHT',
				buffGrowthY             = 'DOWN',
				buffStackPos            = 'BOTTOMRIGHT',
				showDebuffType          = true,
			}),

			focus = Merge(UnitFrameBase, {
				width                   = 186,
				height                  = 80,
				powerHeight             = 8,
				nameTextSize            = 11,
				healthTextSize          = 11,
				powerTextSize           = 9,
				position                = { point = 'CENTER', relPoint = 'CENTER', x = -302, y = 95 },
				showDebuffs             = true,
				showBuffs               = false,
				debuffShowMode          = 'mine',
				buffShowMode            = 'all',
				auraIconSize            = 20,
				auraSpacing             = 2,
				auraStackSize           = 10,
				auraCdSize              = 10,
				maxDebuffs              = 6,
				maxBuffs                = 6,
				debuffsPerRow           = 6,
				buffsPerRow             = 6,
				buffAnchorPoint         = 'BOTTOMLEFT',
				buffOffsetX             = 0,
				buffOffsetY             = -4,
				buffGrowthX             = 'RIGHT',
				buffGrowthY             = 'DOWN',
				showDebuffType          = true,
			}),

			focustarget = Merge(UnitFrameBase, {
				enabled        = false,
				width          = 100,
				height         = 25,
				showHealthText = false,
				nameTextSize   = 10,
				healthTextSize = 10,
				powerTextSize  = 8,
				position       = { point = 'CENTER', relPoint = 'CENTER', x = -420, y = -100 },
			}),

			pet = Merge(UnitFrameBase, {
				width          = 105,
				height         = 41,
				powerHeight    = 8,
				showPower      = true,
				showPowerText  = true,
				nameTextSize   = 10,
				healthTextSize = 10,
				powerTextSize  = 8,
				classColorName = true,
				customName     = '',
				position       = { point = 'CENTER', relPoint = 'CENTER', x = -480, y = -195 },
			}),

			boss = Merge(UnitFrameBase, {
				targetBorder         = { enabled = true, color = { 1, 1, 1, 1 }, thickness = 2 },
				width                = 291,
				height               = 40,
				powerHeight          = 8,
				nameTextSize         = 11,
				healthTextSize       = 10,
				powerTextSize        = 9,
				showPower            = true,
				showPowerText        = true,
				classColorName       = true,
				growthDirection      = 'DOWN',
				spacing              = 1,
				position             = { point = 'CENTER', relPoint = 'CENTER', x = 581, y = 60 },
				showDebuffs          = true,
				debuffShowMode       = 'mine',
				auraIconSize         = 20,
				auraSpacing          = 2,
				auraStackSize        = 10,
				auraCdSize           = 10,
				maxDebuffs           = 6,
				debuffsPerRow        = 6,
				debuffStackPos       = 'BOTTOMRIGHT',
				showDebuffType       = true,
			}),
		},
	},
}

local secondaryPower = BUI.Defaults.profile.secondaryPower
for _, entry in ipairs({
	{ 'combo',          1.00, 0.96, 0.41 },
	{ 'vengeanceFrags', 0.74, 0.27, 0.99, showMax = false, numberOnly = false },
	{ 'holy',           0.95, 0.90, 0.60 },
	{ 'arcane',         0.40, 0.70, 1.00 },
	{ 'shard',          0.65, 0.45, 1.00 },
	{ 'essence',        0.20, 0.85, 0.70 },
	{ 'chi',            0.20, 0.85, 0.70 },
	{ 'mwStacks',       0.20, 0.85, 0.70 },
	{ 'icicles',        0.60, 0.85, 1.00 },
}) do
	local prefix = entry[1]
	secondaryPower[prefix .. 'TotalWidth']     = 222
	secondaryPower[prefix .. 'Height']         = 12
	secondaryPower[prefix .. 'Spacing']        = 2
	secondaryPower[prefix .. 'ShowMax']        = entry.showMax ~= false
	secondaryPower[prefix .. 'NumberOnly']     = entry.numberOnly ~= false
	secondaryPower[prefix .. 'ColorR']         = entry[2]
	secondaryPower[prefix .. 'ColorG']         = entry[3]
	secondaryPower[prefix .. 'ColorB']         = entry[4]
	secondaryPower[prefix .. 'BgColorR']       = 0.15
	secondaryPower[prefix .. 'BgColorG']       = 0.15
	secondaryPower[prefix .. 'BgColorB']       = 0.15
	secondaryPower[prefix .. 'BgColorA']       = 1
	secondaryPower[prefix .. 'BarOffsetX']     = 0
	secondaryPower[prefix .. 'BarOffsetY']     = 0
	secondaryPower[prefix .. 'HideBarText']    = false
	secondaryPower[prefix .. 'CenterTextSize'] = 16
	secondaryPower[prefix .. 'ValueColorR']    = 1
	secondaryPower[prefix .. 'ValueColorG']    = 1
	secondaryPower[prefix .. 'ValueColorB']    = 1
	secondaryPower[prefix .. 'ValueOffsetX']   = 0
	secondaryPower[prefix .. 'ValueOffsetY']   = 0
end
secondaryPower.comboChargedColorR = 0.96
secondaryPower.comboChargedColorG = 0.55
secondaryPower.comboChargedColorB = 0.73

BUI.NilDefaultKeys = {
	minimapScreenX    = true,
	minimapScreenY    = true,
	minimapPos        = true,
	cdmFont           = true,
	trackingFont      = true,
	powerFont         = true,
	secondaryPowerFont = true,
	spellQueueWindow  = true,
	fontPath          = true,
	keybind           = true,
	powerBgColor      = true,
	debuffIconSize    = true,
	debuffSpacing     = true,
	debuffStackSize   = true,
	debuffCdSize      = true,
	debuffShowStack   = true,
	debuffShowCd      = true,
	buffIconSize      = true,
	buffSpacing       = true,
	buffStackSize     = true,
	buffCdSize        = true,
	buffShowStack     = true,
	buffShowCd        = true,
	spellNameMaxLength = true,
	nameFormat        = true,
}

BUI.DeprecatedKeys = {
	['socialFavoritesOnly']     = true,
	['weeklyMplusHistoryView']  = true,

	['powerBar.opacity']        = true,
	['secondaryPower.opacity']  = true,
	['unitFrames.opacity']      = true,
	['cdm.essential.opacity']   = true,

	['cdm.buffs.hideUnavailable']     = true,
	['cdm.buffs.opacity']             = true,
	['cdm.buffs.showOnlyOnCD']        = true,
	['cdm.desatColor']                = true,
	['cdm.essential.hideUnavailable'] = true,
	['cdm.essential.manualBuffs']     = true,
	['cdm.swipeColor']                = true,
	['cdm.utility.opacity']           = true,

	['cursor.hideDuringCinematic'] = true,
	['cursor.hideOnMouselook']     = true,
	['cursor.perButtonColor']      = true,
	['cursor.pulseDuration']       = true,
	['cursor.pulseScale']          = true,
	['cursor.rotate']              = true,
	['cursor.targetAwareColor']    = true,
	['cursor.texture']             = true,
	['cursor.trailEnabled']        = true,
	['cursor.useClassColor']       = true,

	['cursor.outlineOffset']    = true,
	['cursor.clickSpacing']     = true,
	['cursor.clickThickness']   = true,
	['cursor.frameStrata']      = true,
	['cursor.frameLevel']       = true,
	['cursor.gcd']              = true,
	['cursor.gcd.spacing']      = true,
	['cursor.gcd.thickness']    = true,
	['cursor.gcd.dimAlpha']     = true,
	['cursor.gcd.frameLevel']   = true,
	['cursor.gcd.enabled']      = true,
	['cursor.gcd.offset']       = true,
	['cursor.gcd.colorR']       = true,
	['cursor.gcd.colorG']       = true,
	['cursor.gcd.colorB']       = true,
	['cursor.gcd.alpha']        = true,
	['cursor.colorR']           = true,
	['cursor.colorG']           = true,
	['cursor.colorB']           = true,
	['cursor.alpha']            = true,
	['cursor.showOutline']      = true,
	['cursor.outlineSize']      = true,
	['cursor.outlineColorR']    = true,
	['cursor.outlineColorG']    = true,
	['cursor.outlineColorB']    = true,
	['cursor.outlineAlpha']     = true,
	['cursor.cast']             = true,
	['cursor.cast.enabled']     = true,
	['cursor.cast.offset']      = true,
	['cursor.cast.spacing']     = true,
	['cursor.cast.thickness']   = true,
	['cursor.cast.dimAlpha']    = true,
	['cursor.cast.frameLevel']  = true,
	['cursor.cast.colorR']      = true,
	['cursor.cast.colorG']      = true,
	['cursor.cast.colorB']      = true,
	['cursor.cast.alpha']       = true,
	['cursor.cast.channelR']    = true,
	['cursor.cast.channelG']    = true,
	['cursor.cast.channelB']    = true,
	['cursor.cast.channelAlpha']= true,
	['cursor.cast.lockedR']     = true,
	['cursor.cast.lockedG']     = true,
	['cursor.cast.lockedB']     = true,
	['cursor.cast.lockedAlpha'] = true,

	['automation.autoLoot']              = true,
	['battleRezTimer']                   = true,
	['buffTrackingOpacity']              = true,
	['general.addonFont']                = true,
	['general.syncAllVisibility']        = true,
	['general.visibilitySelection']      = true,
	['huntersMark']                      = true,
	['minimapRecentTracking']            = true,
	['interface.drawerDesaturate']       = true,
	['interface.buttonBar.desaturate']   = true,
	['notes']                            = true,

	['unitFrames.boss.bgColor']            = true,
	['unitFrames.boss.borderColor']        = true,
	['unitFrames.boss.classColorHealth']   = true,
	['unitFrames.boss.classColorPower']    = true,
	['unitFrames.boss.healthBarAlpha']     = true,
	['unitFrames.boss.healthColor']        = true,
	['unitFrames.boss.transparentHealth']  = true,
	['unitFrames.focus.bgColor']           = true,
	['unitFrames.focus.borderColor']       = true,
	['unitFrames.focus.classColorHealth']  = true,
	['unitFrames.focus.classColorPower']   = true,
	['unitFrames.focus.healthBarAlpha']    = true,
	['unitFrames.focus.healthColor']       = true,
	['unitFrames.focus.transparentHealth'] = true,
	['unitFrames.focustarget.bgColor']            = true,
	['unitFrames.focustarget.borderColor']        = true,
	['unitFrames.focustarget.classColorHealth']   = true,
	['unitFrames.focustarget.healthBarAlpha']     = true,
	['unitFrames.focustarget.healthColor']        = true,
	['unitFrames.focustarget.transparentHealth']  = true,
	['unitFrames.pet.bgColor']            = true,
	['unitFrames.pet.borderColor']        = true,
	['unitFrames.pet.classColorHealth']   = true,
	['unitFrames.pet.classColorPower']    = true,
	['unitFrames.pet.healthBarAlpha']     = true,
	['unitFrames.pet.healthColor']        = true,
	['unitFrames.pet.transparentHealth']  = true,
	['unitFrames.player.bgColor']           = true,
	['unitFrames.player.borderColor']       = true,
	['unitFrames.player.classColorHealth']  = true,
	['unitFrames.player.classColorPower']   = true,
	['unitFrames.player.healthBarAlpha']    = true,
	['unitFrames.player.healthColor']       = true,
	['unitFrames.player.showDebuffs']       = true,
	['unitFrames.player.transparentHealth'] = true,
	['unitFrames.target.bgColor']           = true,
	['unitFrames.target.borderColor']       = true,
	['unitFrames.target.classColorHealth']  = true,
	['unitFrames.target.classColorPower']   = true,
	['unitFrames.target.healthBarAlpha']    = true,
	['unitFrames.target.healthColor']       = true,
	['unitFrames.target.transparentHealth'] = true,
	['unitFrames.targettarget.bgColor']            = true,
	['unitFrames.targettarget.borderColor']        = true,
	['unitFrames.targettarget.classColorHealth']   = true,
	['unitFrames.targettarget.classColorPower']    = true,
	['unitFrames.targettarget.healthBarAlpha']     = true,
	['unitFrames.targettarget.healthColor']        = true,
	['unitFrames.targettarget.transparentHealth']  = true,
}

BUI.LiveOverrideKeys = {
	['general.colorPickerFavorites'] = true,
}
