local _, BUI = ...

BUI.SearchIndex = {}
local SearchIndex = BUI.SearchIndex

local entries = {
	{ label = "Enable", page = "unitframes", tab = 1, panel = "Enable", keywords = "unit frame" },
	{ label = "Test Mode", page = "unitframes", tab = 1, panel = "Enable" },
	{ label = "Bar Texture", page = "unitframes", tab = 1, panel = "General", keywords = "statusbar texture" },
	{ label = "Font", page = "unitframes", tab = 1, panel = "General" },
	{ label = "Smooth Bars", page = "settings", tab = 1, panel = "Bar Textures", keywords = "animation smooth unit frames group frames" },
	{ label = "Show Tooltips", page = "unitframes", tab = 1, panel = "General", keywords = "aura buff debuff tooltip" },
	{ label = "Decimal Abbreviations", page = "unitframes", tab = 1, panel = "General" },
	{ label = "Exclude Pet from Sync", page = "unitframes", tab = 1, panel = "Synchronization" },
	{ label = "Class Color Health", page = "unitframes", tab = 1, panel = "Health Bar", keywords = "class color" },
	{ label = "Color", page = "unitframes", tab = 1, panel = "Health Bar" },
	{ label = "Border Color", page = "unitframes", tab = 1, panel = "Health Bar" },
	{ label = "Transparent Health", page = "unitframes", tab = 1, panel = "Health Bar" },
	{ label = "Health Fill Opacity %", page = "unitframes", tab = 1, panel = "Health Bar", keywords = "opacity alpha" },
	{ label = "Shield Direction", page = "unitframes", tab = 1, panel = "Absorb & Shields" },
	{ label = "Color by Resource Type", page = "unitframes", tab = 1, panel = "Power Colors" },
	{ label = "Color by Class/Reaction", page = "unitframes", tab = 1, panel = "Power Colors" },
	{ label = "Color", page = "unitframes", tab = 1, panel = "Power Colors" },
	{ label = "Health Color", page = "unitframes", tab = 1, panel = "Pet Colors" },
	{ label = "Health Background", page = "unitframes", tab = 1, panel = "Pet Colors" },
	{ label = "Power Color", page = "unitframes", tab = 1, panel = "Pet Colors" },
	{ label = "Power Background", page = "unitframes", tab = 1, panel = "Pet Colors" },
	{ label = "Border Color", page = "unitframes", tab = 1, panel = "Pet Colors" },
	{ label = "Name Tag", page = "unitframes", tab = 1, panel = "Default Tags", keywords = "tag format name" },
	{ label = "Health Tag", page = "unitframes", tab = 1, panel = "Default Tags", keywords = "tag format health" },
	{ label = "Power Tag", page = "unitframes", tab = 1, panel = "Default Tags", keywords = "tag format power" },
	{ label = "Mode", page = "unitframes", tab = 1, panel = "Raid Icon", keywords = "raid icon skull" },
	{ label = "Position", page = "unitframes", tab = 1, panel = "Raid Icon" },
	{ label = "X Offset", page = "unitframes", tab = 1, panel = "Raid Icon" },
	{ label = "Y Offset", page = "unitframes", tab = 1, panel = "Raid Icon" },
	{ label = "Size", page = "unitframes", tab = 1, panel = "Raid Icon" },
	{ label = "Custom Tags", page = "unitframes", tab = 3, panel = "Custom Tags", keywords = "custom tag text fontstring" },
	{ label = "Enable", page = "unitframes", tab = 4, panel = "Enable", keywords = "player frame" },
	{ label = "Preview", page = "unitframes", tab = 4, panel = "Enable" },
	{ label = "Hide Raid Icon", page = "unitframes", tab = 4, panel = "General" },
	{ label = "Hide Level Text", page = "unitframes", tab = 4, panel = "General" },
	{ label = "Combat Border", page = "unitframes", tab = 4, panel = "General" },
	{ label = "Combat Border Color", page = "unitframes", tab = 4, panel = "General" },
	{ label = "Aggro Border", page = "unitframes", tab = 4, panel = "General", keywords = "aggro threat red border tank" },
	{ label = "Aggro Border Color", page = "unitframes", tab = 4, panel = "General" },
	{ label = "Enabled", page = "unitframes", tab = 4, panel = "Dispel Highlight", keywords = "dispel debuff highlight" },
	{ label = "Color Border", page = "unitframes", tab = 4, panel = "Dispel Highlight" },
	{ label = "Dispellable By Me", page = "unitframes", tab = 4, panel = "Dispel Highlight" },
	{ label = "Dispel Icon", page = "unitframes", tab = 4, panel = "Dispel Highlight", keywords = "badge dispel type icon" },
	{ label = "Type Colors", page = "unitframes", tab = 4, panel = "Dispel Highlight", keywords = "dispel color magic curse poison disease bleed shared palette" },
	{ label = "X Position", page = "unitframes", tab = 4, panel = "Position & Size" },
	{ label = "Y Position", page = "unitframes", tab = 4, panel = "Position & Size" },
	{ label = "Width", page = "unitframes", tab = 4, panel = "Position & Size" },
	{ label = "Height", page = "unitframes", tab = 4, panel = "Position & Size" },
	{ label = "Class/Reaction Color", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "Custom Name", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "Tag Override", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "Position", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "Text Size", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "X Offset", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "Y Offset", page = "unitframes", tab = 4, panel = "Name Text" },
	{ label = "Tag Override", page = "unitframes", tab = 4, panel = "Health Text" },
	{ label = "Position", page = "unitframes", tab = 4, panel = "Health Text" },
	{ label = "Text Size", page = "unitframes", tab = 4, panel = "Health Text" },
	{ label = "Show Power Bar", page = "unitframes", tab = 4, panel = "Power Bar" },
	{ label = "Bar Height", page = "unitframes", tab = 4, panel = "Power Bar" },
	{ label = "Reverse Swipe", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Color by Type", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Max Icons", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Per Row", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Icon Size", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Spacing", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Anchor Point", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Growth Direction", page = "unitframes", tab = 4, panel = "Debuffs" },
	{ label = "Max Icons", page = "unitframes", tab = 4, panel = "Buffs" },
	{ label = "Per Row", page = "unitframes", tab = 4, panel = "Buffs" },
	{ label = "Icon Size", page = "unitframes", tab = 4, panel = "Buffs" },
	{ label = "Anchor Point", page = "unitframes", tab = 4, panel = "Buffs" },
	{ label = "Growth Direction", page = "unitframes", tab = 4, panel = "Buffs" },
	{ label = "Enable", page = "unitframes", tab = 5, panel = "Enable", keywords = "target frame" },
	{ label = "Preview", page = "unitframes", tab = 5, panel = "Enable" },
	{ label = "X Position", page = "unitframes", tab = 5, panel = "Position & Size" },
	{ label = "Y Position", page = "unitframes", tab = 5, panel = "Position & Size" },
	{ label = "Width", page = "unitframes", tab = 5, panel = "Position & Size" },
	{ label = "Height", page = "unitframes", tab = 5, panel = "Position & Size" },
	{ label = "Show Power Bar", page = "unitframes", tab = 5, panel = "Power Bar" },
	{ label = "Enable", page = "unitframes", tab = 6, panel = "Enable", keywords = "target of target tot" },
	{ label = "Anchor Frame", page = "unitframes", tab = 6, panel = "Anchor to Frame" },
	{ label = "Width", page = "unitframes", tab = 6, panel = "Position & Size" },
	{ label = "Height", page = "unitframes", tab = 6, panel = "Position & Size" },
	{ label = "Enable", page = "unitframes", tab = 7, panel = "Enable", keywords = "focus frame" },
	{ label = "Anchor Frame", page = "unitframes", tab = 7, panel = "Anchor to Frame" },
	{ label = "Width", page = "unitframes", tab = 7, panel = "Position & Size" },
	{ label = "Height", page = "unitframes", tab = 7, panel = "Position & Size" },
	{ label = "Enable", page = "unitframes", tab = 8, panel = "Enable", keywords = "pet frame" },
	{ label = "Anchor Frame", page = "unitframes", tab = 8, panel = "Anchor to Frame" },
	{ label = "Custom Name", page = "unitframes", tab = 8, panel = "Name Text" },
	{ label = "Width", page = "unitframes", tab = 8, panel = "Position & Size" },
	{ label = "Height", page = "unitframes", tab = 8, panel = "Position & Size" },
	{ label = "Enable", page = "unitframes", tab = 9, panel = "Enable", keywords = "boss frame" },
	{ label = "Width", page = "unitframes", tab = 9, panel = "Position & Size" },
	{ label = "Height", page = "unitframes", tab = 9, panel = "Position & Size" },
	{ label = "Growth Direction", page = "unitframes", tab = 9, panel = "Stacking" },
	{ label = "Spacing", page = "unitframes", tab = 9, panel = "Stacking" },
	{ label = "Enable", page = "unitframes", tab = 9, panel = "Cast Bar", keywords = "boss cast bar" },
	{ label = "Show Icon", page = "unitframes", tab = 9, panel = "Cast Bar" },
	{ label = "Texture", page = "unitframes", tab = 9, panel = "Cast Bar" },
	{ label = "Height", page = "unitframes", tab = 9, panel = "Cast Bar" },
	{ label = "Non-Interruptible", page = "unitframes", tab = 9, panel = "Cast Bar Colors" },
	{ label = "Interrupt On CD", page = "unitframes", tab = 9, panel = "Cast Bar Colors" },
	{ label = "Target Border", page = "unitframes", tab = 9, panel = "Boss Frames", keywords = "boss target highlight border selected" },

	{ label = "Sync Settings", page = "cdm", tab = 1, panel = "Behavior", keywords = "cooldown manager" },
	{ label = "Move Icons Individually", page = "cdm", tab = 1, panel = "Behavior", keywords = "detach drag" },
	{ label = "Resize Detached Icons", page = "cdm", tab = 1, panel = "Behavior" },
	{ label = "Disable Snapping", page = "cdm", tab = 1, panel = "Behavior" },
	{ label = "Blizzard Panel Overlay", page = "cdm", tab = 1, panel = "Display" },
	{ label = "Font", page = "cdm", tab = 1, panel = "Display" },
	{ label = "Preview", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Color", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Style", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Speed", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Scale", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Lines", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Thickness", page = "cdm", tab = 1, panel = "Glow Settings" },
	{ label = "Enable", page = "cdm", tab = 1, panel = "Assisted Highlight", keywords = "assist highlight" },
	{ label = "Color", page = "cdm", tab = 1, panel = "Assisted Highlight" },
	{ label = "Cooldown Flash", page = "cdm", tab = 1, panel = "Cooldown Appearance" },
	{ label = "Cooldown Edge", page = "cdm", tab = 1, panel = "Cooldown Appearance" },
	{ label = "Enable", page = "cdm", tab = 2, panel = "General", keywords = "essential cooldown" },
	{ label = "X Position", page = "cdm", tab = 2, panel = "Position" },
	{ label = "Y Position", page = "cdm", tab = 2, panel = "Position" },
	{ label = "Center Horizontally", page = "cdm", tab = 2, panel = "Position" },
	{ label = "Vertical", page = "cdm", tab = 2, panel = "Layout" },
	{ label = "Row Growth", page = "cdm", tab = 2, panel = "Layout" },
	{ label = "Row 1 Count", page = "cdm", tab = 2, panel = "Layout", keywords = "icons per row" },
	{ label = "Row 2 Count", page = "cdm", tab = 2, panel = "Layout" },
	{ label = "Row 3 Count", page = "cdm", tab = 2, panel = "Layout" },
	{ label = "Center Last Row", page = "cdm", tab = 2, panel = "Layout" },
	{ label = "Icon Width", page = "cdm", tab = 2, panel = "Appearance", keywords = "icon size" },
	{ label = "Icon Height", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "Spacing", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "Zoom %", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "Border", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "Keep Aspect Ratio", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "Reverse Swipe", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "Border Color", page = "cdm", tab = 2, panel = "Appearance" },
	{ label = "CD Size", page = "cdm", tab = 2, panel = "Text" },
	{ label = "Stack Position", page = "cdm", tab = 2, panel = "Text" },
	{ label = "Stack Size", page = "cdm", tab = 2, panel = "Text" },
	{ label = "Decimal Threshold", page = "cdm", tab = 2, panel = "Text", keywords = "decimal threshold seconds" },
	{ label = "Show", page = "cdm", tab = 2, panel = "Keybind Display", keywords = "keybind hotkey" },
	{ label = "Anchor", page = "cdm", tab = 2, panel = "Keybind Display" },
	{ label = "Font", page = "cdm", tab = 2, panel = "Keybind Display" },
	{ label = "Font Size", page = "cdm", tab = 2, panel = "Keybind Display" },
	{ label = "Offset X", page = "cdm", tab = 2, panel = "Keybind Display" },
	{ label = "Offset Y", page = "cdm", tab = 2, panel = "Keybind Display" },
	{ label = "Color", page = "cdm", tab = 2, panel = "Keybind Display" },
	{ label = "Enable", page = "cdm", tab = 3, panel = "General", keywords = "utility cooldown" },
	{ label = "X Position", page = "cdm", tab = 3, panel = "Position" },
	{ label = "Y Position", page = "cdm", tab = 3, panel = "Position" },
	{ label = "Center Horizontally", page = "cdm", tab = 3, panel = "Position" },
	{ label = "Vertical", page = "cdm", tab = 3, panel = "Layout" },
	{ label = "Row Growth", page = "cdm", tab = 3, panel = "Layout" },
	{ label = "Row 1 Count", page = "cdm", tab = 3, panel = "Layout" },
	{ label = "Icon Width", page = "cdm", tab = 3, panel = "Appearance" },
	{ label = "Icon Height", page = "cdm", tab = 3, panel = "Appearance" },
	{ label = "Spacing", page = "cdm", tab = 3, panel = "Appearance" },
	{ label = "Border", page = "cdm", tab = 3, panel = "Appearance" },
	{ label = "Border Color", page = "cdm", tab = 3, panel = "Appearance" },
	{ label = "CD Size", page = "cdm", tab = 3, panel = "Text" },
	{ label = "Decimal Threshold", page = "cdm", tab = 3, panel = "Text", keywords = "decimal threshold seconds" },
	{ label = "Show", page = "cdm", tab = 3, panel = "Keybind Display" },
	{ label = "Font Size", page = "cdm", tab = 3, panel = "Keybind Display" },
	{ label = "Enable", page = "cdm", tab = 4, panel = "General", keywords = "buff tracker cooldown" },
	{ label = "Preview", page = "cdm", tab = 4, panel = "General" },
	{ label = "Anchor Frame", page = "cdm", tab = 4, panel = "Anchor to Frame" },
	{ label = "Anchor Point", page = "cdm", tab = 4, panel = "Anchor to Frame" },
	{ label = "X Position", page = "cdm", tab = 4, panel = "Position" },
	{ label = "Y Position", page = "cdm", tab = 4, panel = "Position" },
	{ label = "Center Horizontally", page = "cdm", tab = 4, panel = "Position" },
	{ label = "Icon Width", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Icon Height", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Spacing", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Zoom %", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Border", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Keep Aspect Ratio", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Reverse Swipe", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "Border Color", page = "cdm", tab = 4, panel = "Appearance" },
	{ label = "CD Size", page = "cdm", tab = 4, panel = "Text" },
	{ label = "Stack Position", page = "cdm", tab = 4, panel = "Text" },
	{ label = "Stack Size", page = "cdm", tab = 4, panel = "Text" },

	{ label = "Preview", page = "cdm", tab = 5, panel = "Enable", keywords = "show hide dummy bars test" },
	{ label = "Anchor Frame", page = "cdm", tab = 5, panel = "Anchor to Frame", keywords = "attach parent" },
	{ label = "Anchor Point", page = "cdm", tab = 5, panel = "Anchor to Frame" },
	{ label = "Anchor X", page = "cdm", tab = 5, panel = "Anchor to Frame" },
	{ label = "Anchor Y", page = "cdm", tab = 5, panel = "Anchor to Frame" },
	{ label = "Match Anchor Width", page = "cdm", tab = 5, panel = "Anchor to Frame", keywords = "stretch fill width" },
	{ label = "Grow Direction", page = "cdm", tab = 5, panel = "Position", keywords = "up down" },
	{ label = "Center Horizontally", page = "cdm", tab = 5, panel = "Position" },
	{ label = "X Position", page = "cdm", tab = 5, panel = "Position" },
	{ label = "Y Position", page = "cdm", tab = 5, panel = "Position" },
	{ label = "Icon Size", page = "cdm", tab = 5, panel = "Size" },
	{ label = "Bar Width", page = "cdm", tab = 5, panel = "Size" },
	{ label = "Bar Height", page = "cdm", tab = 5, panel = "Size" },
	{ label = "Spacing", page = "cdm", tab = 5, panel = "Size", keywords = "distance apart gap" },
	{ label = "Border", page = "cdm", tab = 5, panel = "Appearance" },
	{ label = "Border Color", page = "cdm", tab = 5, panel = "Appearance" },
	{ label = "Background Color", page = "cdm", tab = 5, panel = "Appearance" },
	{ label = "Class Color Bar", page = "cdm", tab = 5, panel = "Appearance", keywords = "class color bar" },
	{ label = "Bar Color", page = "cdm", tab = 5, panel = "Appearance" },
	{ label = "Name Size", page = "cdm", tab = 5, panel = "Text" },
	{ label = "Show Stacks", page = "cdm", tab = 5, panel = "Text", keywords = "buff bar stacks applications" },
	{ label = "Stack Size", page = "cdm", tab = 5, panel = "Text", keywords = "buff bar stack text size" },

	{ label = "Enable", page = "castbars", tab = 1, keywords = "cast bar player" },
	{ label = "Show Anchor", page = "castbars", tab = 1, keywords = "anchor mover unlock position" },
	{ label = "Anchor Frame", page = "castbars", tab = 1, panel = "Anchor" },
	{ label = "Match Anchor Width", page = "castbars", tab = 1, panel = "Anchor" },
	{ label = "X Position", page = "castbars", tab = 1, panel = "Position" },
	{ label = "Y Position", page = "castbars", tab = 1, panel = "Position" },
	{ label = "Texture", page = "castbars", tab = 1, panel = "Size & Appearance" },
	{ label = "Width", page = "castbars", tab = 1, panel = "Size & Appearance" },
	{ label = "Height", page = "castbars", tab = 1, panel = "Size & Appearance" },
	{ label = "Text Size", page = "castbars", tab = 1, panel = "Size & Appearance" },
	{ label = "Border Size", page = "castbars", tab = 1, panel = "Size & Appearance" },
	{ label = "Bar Color", page = "castbars", tab = 1, panel = "Colors" },
	{ label = "Border Color", page = "castbars", tab = 1, panel = "Colors" },
	{ label = "Background Color", page = "castbars", tab = 1, panel = "Colors" },
	{ label = "Use Class Color", page = "castbars", tab = 1, panel = "Colors" },
	{ label = "Show Icon", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Show Timer", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Show Total Time", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Countdown", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Show Spell Name", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Name Max Length", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Show Latency", page = "castbars", tab = 1, panel = "Display Options", keywords = "lag latency" },
	{ label = "Latency Color", page = "castbars", tab = 1, panel = "Display Options" },
	{ label = "Line Width", page = "castbars", tab = 1, panel = "Empowered Stages", cond = "empower", keywords = "empowered pip" },
	{ label = "Glow", page = "castbars", tab = 1, panel = "Empowered Stages", cond = "empower" },
	{ label = "Pip Color", page = "castbars", tab = 1, panel = "Empowered Stages", cond = "empower" },
	{ label = "Enable", page = "castbars", tab = 1, panel = "Empowered Stages", cond = "empower", keywords = "empowered stage colors background" },
	{ label = "Enable", page = "castbars", tab = 1, panel = "Custom Spell Colors" },
	{ label = "Enable", page = "castbars", tab = 2, keywords = "cast bar target" },
	{ label = "Width", page = "castbars", tab = 2, panel = "Size & Appearance" },
	{ label = "Height", page = "castbars", tab = 2, panel = "Size & Appearance" },
	{ label = "Non-Interruptible", page = "castbars", tab = 2, panel = "Colors", keywords = "interrupt" },
	{ label = "Interrupt On CD", page = "castbars", tab = 2, panel = "Colors" },
	{ label = "Enable", page = "castbars", tab = 3, keywords = "cast bar focus" },
	{ label = "Width", page = "castbars", tab = 3, panel = "Size & Appearance" },
	{ label = "Height", page = "castbars", tab = 3, panel = "Size & Appearance" },
	{ label = "Non-Interruptible", page = "castbars", tab = 3, panel = "Colors" },

	{ label = "Enable", page = "power", tab = 1, keywords = "mana rage energy focus power bar" },
	{ label = "Show Anchor", page = "power", tab = 1, keywords = "anchor mover unlock position" },
	{ label = "Bar Mode", page = "power", tab = 1, panel = "Mode" },
	{ label = "Anchor Frame", page = "power", tab = 1, panel = "Anchor" },
	{ label = "Match Anchor Width", page = "power", tab = 1, panel = "Anchor" },
	{ label = "X Position", page = "power", tab = 1, panel = "Mode", keywords = "position mover" },
	{ label = "Y Position", page = "power", tab = 1, panel = "Mode", keywords = "position mover" },
	{ label = "Center Horizontally", page = "power", tab = 1, panel = "Mode", keywords = "position mover center" },
	{ label = "Width", page = "power", tab = 1, panel = "Mode", keywords = "bar width cog" },
	{ label = "Height", page = "power", tab = 1, panel = "Mode", keywords = "bar height cog" },
	{ label = "Class Color Power", page = "power", tab = 1, panel = "Mode", keywords = "class color cog" },
	{ label = "Color", page = "power", tab = 1, panel = "Mode", keywords = "bar color background prediction swatch" },
	{ label = "Show Value", page = "power", tab = 1, panel = "Text" },
	{ label = "Show Percent", page = "power", tab = 1, panel = "Text" },
	{ label = "Font", page = "power", tab = 1, panel = "Text" },
	{ label = "Text Size", page = "power", tab = 1, panel = "Text" },
	{ label = "Text Color", page = "power", tab = 1, panel = "Text" },
	{ label = "Show % Symbol", page = "power", tab = 1, panel = "Text", keywords = "percent sign symbol" },
	{ label = "Tick Color", page = "power", tab = 1, panel = "Tick Marks", keywords = "tick mark threshold" },
	{ label = "Tick Width", page = "power", tab = 1, panel = "Tick Marks" },
	{ label = "Enable", page = "power", tab = 2, cond = "secondaryPower", keywords = "combo points runes class power secondary stagger" },
	{ label = "Show Anchor", page = "power", tab = 2, cond = "secondaryPower", keywords = "anchor mover unlock position" },
	{ label = "Bar Mode", page = "power", tab = 2, cond = "secondaryPower", panel = "Mode" },
	{ label = "Anchor Frame", page = "power", tab = 2, cond = "secondaryPower", panel = "Anchor" },
	{ label = "X Position", page = "power", tab = 2, cond = "secondaryPower", panel = "Position" },
	{ label = "Y Position", page = "power", tab = 2, cond = "secondaryPower", panel = "Position" },
	{ label = "Center Horizontally", page = "power", tab = 2, cond = "secondaryPower", panel = "Position" },
	{ label = "Width", page = "power", tab = 2, cond = "secondaryPower", panel = "Layout" },
	{ label = "Height", page = "power", tab = 2, cond = "secondaryPower", panel = "Layout" },
	{ label = "Spacing", page = "power", tab = 2, cond = "secondaryPower", panel = "Layout" },
	{ label = "Active Color", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance" },
	{ label = "Empty Color", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance" },
	{ label = "Background", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance" },
	{ label = "Ready Color", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance", keywords = "rune ready" },
	{ label = "Recharging Color", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance", keywords = "rune recharging" },
	{ label = "Light Stagger (0-30%)", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance", keywords = "stagger monk" },
	{ label = "Moderate (30-60%)", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance" },
	{ label = "Heavy Stagger (60%+)", page = "power", tab = 2, cond = "secondaryPower", panel = "Appearance" },
	{ label = "Font", page = "power", tab = 2, cond = "secondaryPower", panel = "Text" },
	{ label = "Text Size", page = "power", tab = 2, cond = "secondaryPower", panel = "Text" },
	{ label = "Text Color", page = "power", tab = 2, cond = "secondaryPower", panel = "Text" },
	{ label = "Show Max", page = "power", tab = 2, cond = "secondaryPower", panel = "Text" },
	{ label = "Tick Color", page = "power", tab = 2, cond = "secondaryPower", panel = "Tick Marks" },
	{ label = "Tick Width", page = "power", tab = 2, cond = "secondaryPower", panel = "Tick Marks" },

	{ label = "Enable", page = "auras", sidebar = "petWarnings", panel = "Pet Warnings", keywords = "pet warning" },
	{ label = "Show Anchor", page = "auras", sidebar = "petWarnings", panel = "Pet Warnings" },
	{ label = "X Position", page = "auras", sidebar = "petWarnings", panel = "Position" },
	{ label = "Y Position", page = "auras", sidebar = "petWarnings", panel = "Position" },
	{ label = "Font", page = "auras", sidebar = "petWarnings", panel = "Appearance" },
	{ label = "Font Size", page = "auras", sidebar = "petWarnings", panel = "Appearance" },
	{ label = "Warning Color", page = "auras", sidebar = "petWarnings", panel = "Appearance" },
	{ label = "Pet Not Attacking", page = "auras", sidebar = "petWarnings", panel = "Warning Types" },
	{ label = "Pet Dead / Missing", page = "auras", sidebar = "petWarnings", panel = "Warning Types" },
	{ label = "Grimoire of Sacrifice", page = "auras", sidebar = "petWarnings", panel = "Warning Types" },
	{ label = "Pet Low Health", page = "auras", sidebar = "petWarnings", panel = "Warning Types" },
	{ label = "Enable", page = "auras", sidebar = "combatTimer", panel = "Combat Timer", keywords = "combat timer" },
	{ label = "Show Anchor", page = "auras", sidebar = "combatTimer", panel = "Combat Timer" },
	{ label = "Font Size", page = "auras", sidebar = "combatTimer", panel = "Appearance" },
	{ label = "Text Color", page = "auras", sidebar = "combatTimer", panel = "Appearance" },
	{ label = "Enable", page = "auras", sidebar = "messages", panel = "Combat Messages", keywords = "combat message text" },
	{ label = "Font Size", page = "auras", sidebar = "messages", panel = "Appearance" },
	{ label = "Fade Time", page = "auras", sidebar = "messages", panel = "Appearance" },
	{ label = "Color", page = "auras", sidebar = "messages", panel = "Appearance" },
	{ label = "Enable", page = "auras", sidebar = "crosshair", panel = "Crosshair", keywords = "crosshair reticle" },
	{ label = "Style", page = "auras", sidebar = "crosshair", panel = "Visibility" },
	{ label = "Hide Out of Combat", page = "auras", sidebar = "crosshair", panel = "Visibility" },
	{ label = "Hide in Town", page = "auras", sidebar = "crosshair", panel = "Visibility" },
	{ label = "Size", page = "auras", sidebar = "crosshair", panel = "Appearance" },
	{ label = "Thickness", page = "auras", sidebar = "crosshair", panel = "Appearance" },
	{ label = "Center Gap", page = "auras", sidebar = "crosshair", panel = "Appearance" },
	{ label = "Opacity", page = "auras", sidebar = "crosshair", panel = "Appearance" },
	{ label = "Color", page = "auras", sidebar = "crosshair", panel = "Appearance" },
	{ label = "Range Indicator", page = "auras", sidebar = "crosshair", panel = "Crosshair", keywords = "melee range ranged out of range color" },
	{ label = "Enable", page = "auras", sidebar = "lowHpWarning", panel = "Low HP Warning", keywords = "low health warning hp" },
	{ label = "Show Anchor", page = "auras", sidebar = "lowHpWarning", panel = "Low HP Warning" },
	{ label = "Threshold %", page = "auras", sidebar = "lowHpWarning", panel = "Low HP Warning" },
	{ label = "Font Size", page = "auras", sidebar = "lowHpWarning", panel = "Appearance" },
	{ label = "Text Color", page = "auras", sidebar = "lowHpWarning", panel = "Appearance" },

	{ label = "Enable", page = "minimap", keywords = "minimap map" },
	{ label = "Show Anchor", page = "minimap", keywords = "anchor mover unlock position" },
	{ label = "Scale", page = "minimap", panel = "Appearance", keywords = "scale size position mover" },
	{ label = "Border Width", page = "minimap", panel = "Appearance", keywords = "border width position mover" },
	{ label = "Indicators", page = "minimap", panel = "Appearance", keywords = "difficulty mail crafting orders garrison mission indicators shape cog" },
	{ label = "24-Hour Format", page = "minimap", panel = "Appearance" },
	{ label = "Server Time", page = "minimap", panel = "Appearance" },
	{ label = "Position", page = "minimap", panel = "Appearance", keywords = "position from right from top rotate show anchor move" },
	{ label = "Enable", page = "minimap", panel = "Datatext", keywords = "datatext minimap bar" },
	{ label = "Modules", page = "minimap", panel = "Datatext", keywords = "datatext modules order ping fps latency" },
	{ label = "Text", page = "minimap", panel = "Datatext", keywords = "datatext font size color anchor position background border" },

	{ label = "Enable", page = "datatext", keywords = "datatext info bar" },
	{ label = "Show Anchor", page = "datatext", keywords = "anchor mover unlock position" },
	{ label = "Selected Bar", page = "datatext", panel = "Bars", keywords = "bar select new add delete second multiple bars" },
	{ label = "Hide Tooltips in Combat", page = "datatext", panel = "Bars", keywords = "tooltip hover combat hide latency friends guild mouseover" },
	{ label = "Roster Tooltips", page = "datatext", panel = "Bars", keywords = "guild friends member tooltip mplus score rank rio hover disable" },
	{ label = "Selected Panel", page = "datatext", panel = "Panels", keywords = "panel blank background square empty new add delete resize" },
	{ label = "Title", page = "datatext", panel = "Panels", keywords = "panel title text label anchor offset size color header" },
	{ label = "Font", page = "datatext", panel = "Style" },
	{ label = "Font Size", page = "datatext", panel = "Style", keywords = "font size cog" },
	{ label = "Spacing", page = "datatext", panel = "Style", keywords = "spacing font cog" },
	{ label = "Orientation", page = "datatext", panel = "Style", keywords = "orientation vertical horizontal text align stack" },
	{ label = "Value Color", page = "datatext", panel = "Style" },
	{ label = "Ping Source", page = "datatext", panel = "Modules", keywords = "ping source home world display modules" },
	{ label = "Display Modules", page = "datatext", panel = "Modules", keywords = "fps framerate ping latency durability gold ilvl item level coords location loot spec memory friends guild modules" },

	{ label = "Enable", page = "cursor", keywords = "cursor ring circle enable" },
	{ label = "Cursor Size", page = "cursor", panel = "General", keywords = "cursor ring size" },
	{ label = "Show Only In Combat", page = "cursor", panel = "General" },

	{ label = "Enable", page = "customBars", tab = 1, panel = "General", keywords = "tracking custom bar item" },
	{ label = "Show Anchor", page = "customBars", tab = 1, panel = "General" },
	{ label = "Show Racials", page = "customBars", tab = 1, panel = "General", keywords = "racial auto add stoneform blood fury escape artist azerite surge will to survive" },
	{ label = "Anchor Frame", page = "customBars", tab = 1, panel = "Anchor to Frame" },
	{ label = "X Position", page = "customBars", tab = 1, panel = "Position" },
	{ label = "Y Position", page = "customBars", tab = 1, panel = "Position" },
	{ label = "Icon Size", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Spacing", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Zoom %", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Border Size", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Grow Direction", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Row Growth", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Max Per Row", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Border Color", page = "customBars", tab = 1, panel = "Layout" },
	{ label = "Show Stacks", page = "customBars", tab = 1, panel = "Text" },
	{ label = "Stack Position", page = "customBars", tab = 1, panel = "Text" },
	{ label = "Stack Size", page = "customBars", tab = 1, panel = "Text" },
	{ label = "CD Size", page = "customBars", tab = 1, panel = "Text" },
	{ label = "Font", page = "customBars", tab = 1, panel = "Text" },

	{ label = "Enable", page = "buffTracking", tab = 1, panel = "General", keywords = "pack leader buff tracking tip spear" },
	{ label = "Show Anchor", page = "buffTracking", tab = 1, panel = "General" },
	{ label = "Bar Mode", page = "buffTracking", tab = 1, panel = "Display Mode" },
	{ label = "Hide When No Stacks", page = "buffTracking", tab = 1, panel = "Visibility" },
	{ label = "Show Only in Combat", page = "buffTracking", tab = 1, panel = "Visibility" },
	{ label = "Bar Width", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Bar Height", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Bar Spacing", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Border Thickness", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Filled Color", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Empty Color", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Border Color", page = "buffTracking", tab = 1, panel = "Bar Settings" },
	{ label = "Text Size", page = "buffTracking", tab = 1, panel = "Text Settings" },
	{ label = "Text Color", page = "buffTracking", tab = 1, panel = "Text Settings" },
	{ label = "X Position", page = "buffTracking", tab = 1, panel = "Position" },
	{ label = "Y Position", page = "buffTracking", tab = 1, panel = "Position" },
	{ label = "Center Horizontally", page = "buffTracking", tab = 1, panel = "Position" },
	{ label = "Color by Stack Count", page = "buffTracking", tab = 1, panel = "Stack Colors" },
	{ label = "Custom Text", page = "buffTracking", tab = 1, panel = "Display", keywords = "precise shots text" },
	{ label = "Enable", page = "buffTracking", tab = 2, panel = "General", keywords = "pack leader" },
	{ label = "Show Anchor", page = "buffTracking", tab = 2, panel = "General" },
	{ label = "Icon Size", page = "buffTracking", tab = 2, panel = "Appearance" },
	{ label = "Spacing", page = "buffTracking", tab = 2, panel = "Appearance" },
	{ label = "Show Only in Combat", page = "buffTracking", tab = 2, panel = "Effects" },
	{ label = "Glow When Ready", page = "buffTracking", tab = 2, panel = "Effects" },
	{ label = "Animate Transitions", page = "buffTracking", tab = 2, panel = "Effects" },
	{ label = "Show Countdown Text", page = "buffTracking", tab = 2, panel = "Effects" },
	{ label = "X Position", page = "buffTracking", tab = 2, panel = "Position" },
	{ label = "Y Position", page = "buffTracking", tab = 2, panel = "Position" },

	{ label = "Enable", page = "auras", tab = 2, panel = "GCD History", keywords = "gcd history streamer" },
	{ label = "Preview", page = "auras", tab = 2, panel = "GCD History", keywords = "gcd anchor unlock drag" },
	{ label = "Icons", page = "auras", tab = 2, panel = "Display", keywords = "gcd icon size max spacing zoom border" },
	{ label = "Grow Direction", page = "auras", tab = 2, panel = "Display", keywords = "gcd left right" },
	{ label = "Border Color", page = "auras", tab = 2, panel = "Display", keywords = "gcd" },
	{ label = "Position", page = "auras", tab = 2, panel = "Display", keywords = "gcd anchor frame offset" },
	{ label = "Active Cast", page = "auras", tab = 2, panel = "Behavior", keywords = "gcd cast scale channel" },
	{ label = "Auto-Expire", page = "auras", tab = 2, panel = "Behavior", keywords = "gcd fade lifetime" },
	{ label = "Hide Auto Attacks", page = "auras", tab = 2, panel = "Behavior", keywords = "gcd" },
	{ label = "Debug to Chat", page = "auras", tab = 2, panel = "Behavior", keywords = "gcd" },
	{ label = "Blacklist", page = "auras", tab = 2, panel = "Blacklist", keywords = "gcd spell ignore" },

	{ label = "Use Class Color", page = "settings", tab = 1, panel = "Accent", keywords = "theme color accent class" },
	{ label = "Accent Color", page = "settings", tab = 1, panel = "Accent", keywords = "theme color accent" },
	{ label = "Global Bar Texture", page = "settings", tab = 1, panel = "Bar Textures", keywords = "texture statusbar" },
	{ label = "Gradient Tint", page = "settings", tab = 1, panel = "Bar Textures", keywords = "gradient color texture" },
	{ label = "Global Font", page = "settings", tab = 1, panel = "Fonts", keywords = "font typeface" },
	{ label = "Slug Rendering", page = "settings", tab = 1, panel = "Fonts", keywords = "font slug outline thick" },
	{ label = "Dispel Type Colors", page = "settings", tab = 1, panel = "Dispel Types", keywords = "dispel magic curse poison disease bleed color shared palette" },
	{ label = "Hotkey Text", page = "actionbars", sidebar = "general", panel = "General > Button Text", keywords = "action bar keybind text size anchor color" },
	{ label = "Count Text", page = "actionbars", sidebar = "general", panel = "General > Button Text", keywords = "action bar stack charges count text" },
	{ label = "Macro Text", page = "actionbars", sidebar = "general", panel = "General > Button Text", keywords = "action bar macro name text" },
	{ label = "Empty Buttons", page = "actionbars", sidebar = "general", panel = "General > Appearance", keywords = "action bar empty slot background opacity" },
	{ label = "Key Presses", page = "actionbars", sidebar = "general", panel = "General > Appearance", keywords = "action bar key press flash" },
	{ label = "Proc Glow", page = "actionbars", sidebar = "general", panel = "General > Effects", keywords = "action bar proc glow cast animation assisted combat" },
	{ label = "Lock Buttons", page = "actionbars", sidebar = "general", panel = "General > Locking & Moving", keywords = "action bar lock pick up key shift" },
	{ label = "Unlock Bars", page = "actionbars", sidebar = "general", panel = "General > Locking & Moving", keywords = "action bar move drag snap" },
	{ label = "Bar Position", page = "actionbars", sidebar = "bar1", panel = "Bar 1 > Layout", keywords = "action bar position anchor center" },
	{ label = "Page Switching", page = "actionbars", sidebar = "bar1", panel = "Bar 1 > Paging", keywords = "action bar paging modifier ctrl alt shift vehicle stance page" },
	{ label = "Pet Bar", page = "actionbars", sidebar = "pet", panel = "Pet Bar", keywords = "pet bar action buttons autocast hunter warlock" },
	{ label = "Stance Bar", page = "actionbars", sidebar = "stance", panel = "Stance Bar", keywords = "stance form shapeshift bar druid warrior" },
	{ label = "Vehicle Exit", page = "actionbars", sidebar = "vehicle", panel = "Vehicle Exit", keywords = "vehicle exit leave taxi possess button" },
	{ label = "Micro Menu", page = "actionbars", sidebar = "micro", panel = "Micro Menu", keywords = "micro menu buttons character spellbook bar" },
	{ label = "Bag Bar", page = "actionbars", sidebar = "bags", panel = "Bag Bar", keywords = "bag bar backpack buttons" },
	{ label = "TTS Volume", page = "settings", tab = 2, panel = "Voice & Sound", keywords = "tts voice speech volume loudness audio" },
	{ label = "Alert Sound Channel", page = "settings", tab = 2, panel = "Voice & Sound", keywords = "sound channel master sfx audio alerts" },
	{ label = "Faster Looting", page = "settings", tab = 2, panel = "Looting", keywords = "loot speed auto fast" },
	{ label = "Auto-Sell Junk", page = "settings", tab = 2, panel = "Looting", keywords = "vendor sell grey trash" },
	{ label = "Auto-Repair", page = "settings", tab = 2, panel = "Merchant", keywords = "repair gold" },
	{ label = "Use Guild Funds", page = "settings", tab = 2, panel = "Merchant" },
	{ label = "Show Repair Cost", page = "settings", tab = 2, panel = "Merchant" },
	{ label = "Auto-Accept & Gossip", page = "settings", tab = 2, panel = "Questing", keywords = "quest auto accept gossip" },
	{ label = "Auto-Complete", page = "settings", tab = 2, panel = "Questing", keywords = "quest auto complete turn in" },
	{ label = "Skip Movies", page = "settings", tab = 2, panel = "Questing", keywords = "cinematic movie skip" },
	{ label = "Cast on Key Down", page = "settings", tab = 2, panel = "Combat", keywords = "key down press" },
	{ label = "Auto Keystone", page = "settings", tab = 2, panel = "Combat", keywords = "mythic keystone auto insert" },
	{ label = "Auto Combat Log", page = "settings", tab = 2, panel = "Combat Logging", keywords = "combat log logging warcraft logs record auto" },
	{ label = "Logging Indicator", page = "settings", tab = 2, panel = "Combat Logging", keywords = "combat log indicator recording dot" },
	{ label = "Advanced Logging", page = "settings", tab = 2, panel = "Combat Logging", keywords = "advanced combat logging warcraft logs cvar" },
	{ label = "Spell Queue (ms)", page = "settings", tab = 2, panel = "Combat", keywords = "spell queue window spellqueue" },
	{ label = "Auto-Accept Party", page = "settings", tab = 2, panel = "Social" },
	{ label = "Include Guild", page = "settings", tab = 2, panel = "Social" },
	{ label = "Auto-Confirm Role", page = "settings", tab = 2, panel = "Social" },
	{ label = "Easy Item Destroy", page = "settings", tab = 2, panel = "Interface", keywords = "delete destroy confirm" },
	{ label = "Hide Talking Head", page = "settings", tab = 2, panel = "Interface" },
	{ label = "Hide Rested Zzz", page = "settings", tab = 2, panel = "Interface" },
	{ label = "Hide Zone Text", page = "settings", tab = 2, panel = "Interface" },
	{ label = "Hide Error Msgs", page = "settings", tab = 2, panel = "Interface", keywords = "error red text" },
	{ label = "Apply FPS Settings", page = "settings", tab = 2, panel = "Graphical Tweaks", keywords = "fps cvar performance graphics vsync" },
	{ label = "Restore Original", page = "settings", tab = 2, panel = "Graphical Tweaks", keywords = "cvar restore reset" },
	{ label = "Hold to Reset Settings", page = "settings", tab = 2, panel = "Danger Zone", keywords = "reset wipe default" },
	{ label = "Unit Frames", page = "settings", tab = 5, panel = "Modules", keywords = "enable disable module" },
	{ label = "Cooldown Manager", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Cast Bars", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Power Bars", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Minimap", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Auras", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Buff Tracking", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Datatext", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Custom Bars", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Cursor", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Streamer Tools", page = "settings", tab = 5, panel = "Modules" },
	{ label = "Gem Manager", page = "settings", tab = 5, panel = "Modules" },

	{ label = "Enable", page = "exportimport", tab = 1, panel = "Spec Profiles", keywords = "export import profile share spec" },

	{ label = "Enable", page = "groupframes", tab = 1, panel = "Group Frames", keywords = "group party raid frames" },
	{ label = "Hide Blizzard Frames", page = "groupframes", tab = 1, panel = "Behavior", keywords = "blizzard default frames hide" },
	{ label = "Click Casting", page = "groupframes", tab = 1, panel = "Behavior", keywords = "click cast mouse clique" },
	{ label = "Missing Raid Buff", page = "groupframes", tab = 4, panel = "Party Auras", keywords = "raid buff missing intellect fortitude" },
	{ label = "Missing Raid Buff", page = "groupframes", tab = 5, panel = "Raid Auras", keywords = "raid buff missing intellect fortitude" },
	{ label = "Fade Out Of Range", page = "groupframes", tab = 1, panel = "Range Fading", keywords = "range fade alpha distance" },
	{ label = "Fade Offline", page = "groupframes", tab = 1, panel = "Range Fading" },
	{ label = "In-Range Alpha", page = "groupframes", tab = 1, panel = "Range Fading" },
	{ label = "Out-Of-Range Alpha", page = "groupframes", tab = 1, panel = "Range Fading" },
	{ label = "Show Self In Party", page = "groupframes", tab = 2, panel = "Layout & Visibility", keywords = "player self party" },
	{ label = "Show When Solo", page = "groupframes", tab = 2, panel = "Layout & Visibility", keywords = "solo" },
	{ label = "Sort By", page = "groupframes", tab = 2, panel = "Layout & Visibility", keywords = "sort role class order" },
	{ label = "Width", page = "groupframes", tab = 2, panel = "Dimensions", keywords = "size party frame" },
	{ label = "Height", page = "groupframes", tab = 2, panel = "Dimensions" },
	{ label = "Frame Spacing", page = "groupframes", tab = 2, panel = "Dimensions", keywords = "spacing gap" },
	{ label = "Show Power Bars", page = "groupframes", tab = 2, panel = "Dimensions", keywords = "power mana bar" },
	{ label = "Mana On Healers Only", page = "groupframes", tab = 2, panel = "Dimensions", keywords = "healer mana" },
	{ label = "Bar Texture", page = "groupframes", tab = 2, panel = "Dimensions", keywords = "statusbar texture" },
	{ label = "Vertical Layout", page = "groupframes", tab = 2, panel = "Dimensions", keywords = "vertical horizontal" },
	{ label = "Anchor Frame", page = "groupframes", tab = 2, panel = "Position", keywords = "anchor attach position party" },
	{ label = "Class Color Health", page = "groupframes", tab = 2, panel = "Health & Colors", keywords = "class color health" },
	{ label = "Border Color", page = "groupframes", tab = 2, panel = "Health & Colors" },
	{ label = "Background Color", page = "groupframes", tab = 2, panel = "Health & Colors" },
	{ label = "Transparent Health", page = "groupframes", tab = 2, panel = "Health & Colors", keywords = "transparent opacity" },
	{ label = "Absorbs", page = "groupframes", tab = 2, panel = "Absorbs", keywords = "absorb shield heal" },
	{ label = "Target Border", page = "groupframes", tab = 2, panel = "Selection Borders", keywords = "target mouseover border highlight" },
	{ label = "Font", page = "groupframes", tab = 2, panel = "Font & Name", keywords = "font name text" },
	{ label = "Health Text", page = "groupframes", tab = 2, panel = "Health Text", keywords = "health percent text format" },
	{ label = "Power Text", page = "groupframes", tab = 2, panel = "Power Text", keywords = "power mana text" },
	{ label = "Status Text", page = "groupframes", tab = 2, panel = "Status Text (Dead / Offline / AFK)", keywords = "dead ghost offline afk dnd status color" },
	{ label = "Indicators", page = "groupframes", tab = 2, panel = "Indicators", keywords = "role leader raid marker resurrect ready check combat icon" },
	{ label = "Unit Tooltips", page = "groupframes", tab = 2, panel = "Tooltips", keywords = "tooltip" },
	{ label = "Aura Tooltips", page = "groupframes", tab = 2, panel = "Tooltips", keywords = "aura buff debuff tooltip" },
	{ label = "Group Spacing", page = "groupframes", tab = 3, panel = "Dimensions", keywords = "raid group spacing" },
	{ label = "Groups Per Row", page = "groupframes", tab = 3, panel = "Dimensions", keywords = "raid groups row column" },
	{ label = "Buffs", page = "groupframes", tab = 4, panel = "Buffs", keywords = "party aura buff icons rules" },
	{ label = "Debuffs", page = "groupframes", tab = 4, panel = "Debuffs", keywords = "party aura debuff icons rules boss" },
	{ label = "Defensives", page = "groupframes", tab = 4, panel = "Defensives", keywords = "party defensive cooldown external big" },
	{ label = "Crowd Control", page = "groupframes", tab = 4, panel = "Crowd Control", keywords = "party cc stun fear crowd control" },
	{ label = "Dispel Highlight", page = "groupframes", tab = 4, panel = "Dispel Highlight", keywords = "dispel debuff highlight border badge magic curse poison disease" },
	{ label = "Dispel Type Colors", page = "groupframes", tab = 4, panel = "Dispel Type Colors", keywords = "dispel color magic curse poison disease bleed shared palette" },
	{ label = "Private Auras", page = "groupframes", tab = 4, panel = "Private Auras", keywords = "private aura raid boss" },
	{ label = "Missing Raid Buff", page = "groupframes", tab = 4, panel = "Missing Raid Buff", keywords = "missing raid buff icon" },
	{ label = "Buffs", page = "groupframes", tab = 5, panel = "Buffs", keywords = "raid aura buff icons rules" },
	{ label = "Debuffs", page = "groupframes", tab = 5, panel = "Debuffs", keywords = "raid aura debuff icons rules boss" },
	{ label = "Defensives", page = "groupframes", tab = 5, panel = "Defensives", keywords = "raid defensive cooldown external big" },
	{ label = "Crowd Control", page = "groupframes", tab = 5, panel = "Crowd Control", keywords = "raid cc stun fear crowd control" },
	{ label = "Dispel Highlight", page = "groupframes", tab = 5, panel = "Dispel Highlight", keywords = "raid dispel highlight border badge" },
	{ label = "Dispel Type Colors", page = "groupframes", tab = 5, panel = "Dispel Type Colors", keywords = "raid dispel color magic curse poison disease bleed shared palette" },
	{ label = "Private Auras", page = "groupframes", tab = 5, panel = "Private Auras", keywords = "raid private aura boss" },
	{ label = "Missing Raid Buff", page = "groupframes", tab = 5, panel = "Missing Raid Buff", keywords = "raid missing buff icon" },
	{ label = "Debuff Blacklist", page = "groupframes", tab = 6, panel = "Debuff Blacklist", keywords = "blacklist filter debuff hide spell recently seen built-in share sated deserter" },
	{ label = "Buff Blacklist", page = "groupframes", tab = 6, panel = "Buff Blacklist", keywords = "blacklist filter buff hide spell recently seen share" },
}

local pageTitles = {}
local tabNames = {}

local HAS_SECONDARY_POWER = {
	DEATHKNIGHT = true, ROGUE = true, WARLOCK = true, PALADIN = true, EVOKER = true,
	DRUID = true, MONK = true, MAGE = true, PRIEST = true, SHAMAN = true,
}
local condChecks = {
	secondaryPower = function()
		local _, className = UnitClass('player')
		return HAS_SECONDARY_POWER[className] == true
	end,
	empower = function()
		return BUI.Tools.PlayerCanEmpower()
	end,
	module = function(moduleName)
		local db = BUI.GetDB()
		if not db then return true end
		return db.modules[moduleName] ~= false
	end,
}
local function CheckCond(condition)
	if not condition then return true end
	local check = condChecks[condition]
	if check then return check() end
	local moduleName = condition:match('^module:(.+)')
	if moduleName then return condChecks.module(moduleName) end
	return true
end

local function EnsureTitles()
	if next(pageTitles) then return end
	local engine = BUI.PageEngine
	if not engine or not engine.pages then return end
	for pageId, pageConfig in pairs(engine.pages) do
		pageTitles[pageId] = pageConfig.buttonText or pageConfig.title or pageId
	end
end

function SearchIndex.RegisterTabNames(pageId, names)
	tabNames[pageId] = names
end

function SearchIndex.Search(query)
	if not query or query == '' then return {} end
	EnsureTitles()
	query = query:lower()
	local results = {}
	for _, entry in ipairs(entries) do
		if CheckCond(entry.cond) then
			local haystack = (entry.label .. ' ' .. (entry.panel or '') .. ' ' .. (pageTitles[entry.page] or entry.page) .. ' ' .. (entry.keywords or '')):lower()
			if haystack:find(query, 1, true) then
				local tabs = tabNames[entry.page]
				local tabName = tabs and tabs[entry.tab] or nil
				if entry.sidebar then tabName = entry.panel end
				results[#results + 1] = {
					label = entry.label,
					page = entry.page,
					pageTitle = pageTitles[entry.page] or entry.page,
					tab = entry.tab,
					sidebar = entry.sidebar,
					tabName = tabName,
					panel = entry.panel,
				}
				if #results >= 30 then break end
			end
		end
	end
	return results
end

SearchIndex.RegisterTabNames('auras', { 'Alerts', 'Bloodlust', 'GCD History' })
SearchIndex.RegisterTabNames('power', { 'Primary', 'Secondary' })
SearchIndex.RegisterTabNames('cdm', { 'General', 'Essential', 'Utility', 'Buffs', 'Buff Bars', 'Layouts', 'Icon Management' })
SearchIndex.RegisterTabNames('castbars', { 'Player', 'Target', 'Focus' })
SearchIndex.RegisterTabNames('unitframes', { 'Global', 'Reference', 'Custom Tags', 'Player', 'Target', 'ToT', 'Focus', 'Pet', 'Boss', 'Filters' })
SearchIndex.RegisterTabNames('groupframes', { 'General', 'Party', 'Raid', 'Party Auras', 'Raid Auras', 'Filters' })
SearchIndex.RegisterTabNames('settings', { 'Settings', 'Appearance', 'Skinning', 'Visibility', 'Modules', 'Help' })
SearchIndex.RegisterTabNames('buffTracking', { 'Tracking' })
